### PR TITLE
Not implemented error with react native

### LINKED ISSUE #3667: How to fix "ReferenceError: btoa is not defined" while running build with Node.js?
### Expected behavior

The bundle `bundle.js` created with the `webpack` should run without error with the command `node bundle.js`.

#### Actual behavior

I'm getting the following error:
```
webpack:///./app/node_modules/web3/node_modules/web3-providers-ws/src/helpers.js?:21
_btoa = btoa.bind(window);
^

ReferenceError: btoa is not defined
at Object.eval (webpack:///./app/node_modules/web3/node_modules/web3-providers-ws/src/helpers.js?:21:5)
at eval (webpack:///./app/node_modules/web3/node_modules/web3-providers-ws/src/helpers.js?:32:30)
at Object../app/node_modules/web3/node_modules/web3-providers-ws/src/helpers.js (C:\Users\User\Desktop\dApp-nodeJS-webpack-master\dist\bundle.js:4491:1)
at webpack_require (C:\Users\User\Desktop\dApp-nodeJS-webpack-master\dist\bundle.js:20:30)
at eval (webpack:///./app/node_modules/web3/node_modules/web3-providers-ws/src/index.js?:26:15)
at Object../app/node_modules/web3/node_modules/web3-providers-ws/src/index.js (C:\Users\User\Desktop\dApp-nodeJS-webpack-master\dist\bundle.js:4503:1)
at webpack_require (C:\Users\User\Desktop\dApp-nodeJS-webpack-master\dist\bundle.js:20:30)
at eval (webpack:///./app/node_modules/web3/node_modules/web3-core-requestmanager/src/index.js?:53:24)
at Object../app/node_modules/web3/node_modules/web3-core-requestmanager/src/index.js (C:\Users\User\Desktop\dApp-nodeJS-webpack-master\dist\bundle.js:4141:1)
at webpack_require (C:\Users\User\Desktop\dApp-nodeJS-webpack-master\dist\bundle.js:20:30)
```

#### Steps to reproduce the behavior

1. `$ git clone https://github.com/olisystems/dApp-nodeJS-webpack.git`
2. `$ cd dApp-nodeJS-webpack`
3. `$ npm install`
4. `$ cd app && npm i`
5. `$ npm run ganache`
6. open the new terminal and run `$ npm run migrate`
7. `$ cd dApp-nodeJS-webpack`
8. `$ npm run dev`
9. open a new terminal and run `cd dist && node bundle.js`

#### Environment

Node.js: 12
Web3: 1.2.11
OS: Windows, Ubunut 20.04

### PR DESCRIPTION
**Pull request by daoauth**
## Description
from
```javascript
var isNode = Object.prototype.toString.call(typeof process !== 'undefined' ? process : 0) === '[object process]';
...

if (isNode) {
   ...
}
```

to
```javascript
var isNode = Object.prototype.toString.call(typeof process !== 'undefined' ? process : 0) === '[object process]';
var isRN = typeof navigator !== 'undefined' && navigator.product === 'ReactNative';
...
if (isNode || isRN) {
   ...
}
```

Fixes #3667 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

File: packages/web3-providers-ws/src/helpers.js [hunk 1]
```diff
@@ -20,7 +20,13 @@ if (isNode) {
 } else {
     _btoa = btoa.bind(window);
     helpers = function(url) {
-        return new URL(url);
+        var parsedUrl = new URL(url);
+        // web3 uses URL's username and password on websocket provider, which are not
+        // implemented by react-native, instead of throwing a `not implemented` error
+        // by default, simply return undefined
+        Object.defineProperty(parsedUrl, 'username', {value:undefined});
+        Object.defineProperty(parsedUrl, 'password', {value:undefined});
```
Comment (GregTheGreek) [inline packages/web3-providers-ws/src/helpers.js]: This will override values IFF `username` and `password` existed.

perhaps adding a check to see if they exist would make sense

**Review by GregTheGreek — CHANGES_REQUESTED** [review]

File: packages/web3-providers-ws/src/helpers.js (hunk 1 above)
Comment (daoauth) [reply packages/web3-providers-ws/src/helpers.js]: Thanks

**Comment by daoauth** [comment]
close and pr again

**Comment by GregTheGreek** [comment]
Can you please update the changelog :)

**Comment by GregTheGreek** [comment]
@daoauth Do you have an example repo I could check out to verify this? I'd love to eventually add react-native support as a part of the CI run...

**Comment by daoauth** [comment]
> @daoauth Do you have an example repo I could check out to verify this? I'd love to eventually add react-native support as a part of the CI run...

[https://github.com/daoauth/web3js-react-native-ws](https://github.com/daoauth/web3js-react-native-ws)

**Review by GregTheGreek — DISMISSED** [review]

**Review by GregTheGreek — DISMISSED** [review]

File: packages/web3-providers-ws/src/helpers.js [hunk 2]
```diff
@@ -19,9 +19,7 @@ if (isNode) {
     }
 } else {
     _btoa = btoa.bind(window);
-    helpers = function(url) {
-        return new URL(url);
-    };
+    helpers = require('url').parse;;
```
Comment (Spacesai1or) [inline packages/web3-providers-ws/src/helpers.js]: Small typo here with the double semicolons

```suggestion
    helpers = require('url').parse;
```

**Review by Spacesai1or — CHANGES_REQUESTED** [review]

**Comment by Spacesai1or** [comment]
Changes seem to follow [documentation](https://nodejs.org/api/url.html#url_url)

**Review by GregTheGreek — APPROVED** [review]

File: packages/web3-providers-ws/src/helpers.js [hunk 3]
```diff
@@ -1,8 +1,9 @@
 var isNode = Object.prototype.toString.call(typeof process !== 'undefined' ? process : 0) === '[object process]';
+var isRN = typeof navigator !== 'undefined' && navigator.product === 'ReactNative';
```
Comment (Spacesai1or) [inline packages/web3-providers-ws/src/helpers.js:2]: Looks like [the correct way](https://stackoverflow.com/questions/39468022/how-do-i-know-if-my-code-is-running-as-react-native) to check if running ReactNative

**Review by Spacesai1or — APPROVED** [review]
