### PR TITLE
Verify that event arg indexing matches received topics

### LINKED ISSUE #3272: A contract call which triggers multiple events of the same name throws error
There is #2933 with exactly same issue i am experiencing.
Turns out that 
`method.extraFormatters.receiptFormatter()` in web3-core-method throws <b>"Error: Returned values aren't valid, did it run Out of Gas?"</b>

I am able to fix it by indexing arguments in same order but it is something that we are not willing to do. 

Please investigate as it seems like that problem was fixed in the past.

web3 1.2.4 
truffle 5.1.3

### PR DESCRIPTION
**Pull request by cgewecke**
## Description

Per #3272, when a transaction sent to one contract triggers an event in another contract whose signature shadows the ABI of calling contract, but whose arguments are indexed differently, Web3 crashes while formatting the receipt's logs because the topics and data don't match expectations.

PR adds logic to verify that the number of indexed args is compatible with the number of received topics. 

Tests are based on the reproduction case in [truffle 1729][1]

[1]: https://github.com/trufflesuite/truffle/issues/1729

Fixes #3272

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran ```npm run dtslint``` with success and extended the tests and types if necessary.
- [x] I ran ```npm run test:unit``` with success and extended the tests if necessary.
- [x] I ran ```npm run build-all``` and tested the resulting file/'s from  ```dist``` folder in a browser.
- [x] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the live network.

### CODE REVIEW

File: packages/web3-eth-contract/src/index.js [hunk 1]
```diff
@@ -450,6 +450,19 @@ Contract.prototype._decodeEventABI = function (data) {
...
+    // arg indexing. If # of topics doesn't match, event is anon.
+    if (!event.anonymous){
+        let indexedInputs = 0;
+        event.inputs.forEach(input => input.indexed ? indexedInputs++ : null);
+
+        if (indexedInputs > 0 && (data.topics.length !== indexedInputs + 1)){
+            event = {
+                anonymous: true,
+                inputs: []
+            }
```
Comment (nivida) [inline packages/web3-eth-contract/src/index.js]: Missing semicolon

File: test/e2e.contract.events.js [hunk 2]
```diff
@@ -70,5 +72,56 @@ describe('contract.events [ @E2E ]', function() {
...
+        const child = await contract.deploy().send({from: accounts[0]});
+
+        options.data = Parent.bytecode;
+        contract = new web3.eth.Contract(Parent.abi, options);
+        const parent = await contract.deploy().send({from: accounts[0]});
+
+        await parent
+            .methods
+            .fireChildSimilarEvent(child.options.address)
+            .send({from: accounts[0]})
```
Comment (nivida) [inline test/e2e.contract.events.js]: Missing semicolon

File: test/e2e.contract.events.js [hunk 3]
```diff
@@ -70,5 +72,56 @@ describe('contract.events [ @E2E ]', function() {
...
+
+        await parent
+            .methods
+            .fireChildIdenticalEvent(child.options.address)
+            .send({from: accounts[0]})
```
Comment (nivida) [inline test/e2e.contract.events.js]: Missing semicolon

**Review by nivida — CHANGES_REQUESTED** [review]
Tested it locally and it LGTM. I've only added three comments to improve the code-style.

**Review by nivida — APPROVED** [review]

**Comment by nivida** [comment]
@cgewecke I've added the missing semicolons quickly 👌
