### PR TITLE
6156 find replacement for is my json valid

### LINKED ISSUE #6156: Find replacement for is-my-json-valid
#### Expected behavior
- library is not browser friendly as it uses dependencies that depend on nodejs "util" as well as "process" global which causes build to fail in angular. Related to #6146 

#### Actual behavior

Using browser friendly library by either forking is-my-json valid or finding some browser friendly validator

#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

### PR DESCRIPTION
**Pull request by avkos**
## Description
Fixes #6156  and #6168
Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../CONTRIBUTIONS.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run lint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

### CODE REVIEW

File: packages/web3-validator/src/types.ts [hunk 1]
```diff
@@ -143,10 +143,7 @@ export type Schema = {
 };
 export interface Validate {
 	(value: Json): boolean;
-	errors?: ValidationError[];
+	errors?: ZodIssueBase[];
```
Comment (jdevcs) [inline packages/web3-validator/src/types.ts]: This will be breaking change, as Validation interface is being exported and available to users. For this during release we will need to bump major version of validator package. so:

1. mention this in changelog
2. I think create some validation error wrapper around `ZodIssueBase` , so we are not tied to specific lib (like we were is-my-json-valid.ValidationError)

File: packages/web3-validator/src/types.ts [hunk 2]
```diff
@@ -143,10 +143,7 @@ export type Schema = {
...
 }
-export type RawValidationError = ValidationError & {
```
Comment (jdevcs) [inline packages/web3-validator/src/types.ts:148]: (breaking change ) it was also exported and will no longer available so : changelog

File: packages/web3-validator/src/validator.ts [hunk 3]
```diff
@@ -16,53 +16,212 @@ along with web3.js.  If not, see <http://www.gnu.org/licenses/>.
...
 		return Validator.validatorInstance;
 	}
-	private readonly _schemas: Map<string, Validate> = new Map();
-	public getSchema(key: string) {
-		return this._schemas.get(key);
-	}
-
-	public addSchema(key: string, schema: Schema) {
-		this._schemas.set(key, this.createValidator(schema));
-	}
```
Comment (jdevcs) [inline packages/web3-validator/src/validator.ts:44]: (its breaking change) For all public functions in this class , add in change log, that these will not be available.

**Comment by jdevcs** [comment]
LGTM, just need some minor changes. 

Plus with zod lib using in this PR, could you manually test some recent issues reported for browser support due to is my json valid lib.

File: packages/web3-validator/src/types.ts (hunk 1 above)
Comment (avkos) [reply packages/web3-validator/src/types.ts]: ValidationError wrapper was added

File: packages/web3-validator/src/validator.ts (hunk 3 above)
Comment (avkos) [reply packages/web3-validator/src/validator.ts:44]: Class Validator is not public to users. It is only for internal Web3Validator usage

File: packages/web3-validator/src/validation/boolean.ts [hunk 4]
```diff
@@ -35,9 +35,6 @@ export const isBoolean = (value: ValidInputTypes) => {
 		return value === '0x1' || value === '0x0';
 	}
 
-	if (typeof value === 'number') {
-		return value === 1 || value === 0;
-	}
-
-	return false;
+	// type === number
+	return value === 1 || value === 0;
```
Comment (avkos) [inline packages/web3-validator/src/validation/boolean.ts:39]: here can be only number type. we don't need extra conditions.

File: packages/web3-validator/src/types.ts (hunk 2 above)
Comment (avkos) [reply packages/web3-validator/src/types.ts:148]: done

**Review by jdevcs — APPROVED** [review]

File: packages/web3-validator/src/validator.ts (hunk 3 above)
Comment (jdevcs) [reply packages/web3-validator/src/validator.ts:44]: at two places:
https://github.com/web3/web3.js/blob/ad377d16a7e9a8e82857d6102bb4efd95c543e4f/packages/web3-validator/src/default_validator.ts#L20
https://github.com/web3/web3.js/blob/ad377d16a7e9a8e82857d6102bb4efd95c543e4f/packages/web3-validator/src/index.ts#L19

and

https://github.com/web3/web3.js/blob/ad377d16a7e9a8e82857d6102bb4efd95c543e4f/packages/web3/src/index.ts#L342

This will be breaking change for main web3 package as well.

**Review by luu-alex — APPROVED** [review]
