### PR TITLE
Filter option doesn't work in getPastEvents

### LINKED ISSUE #5862: Filter option doesn't work in getPastEvents
related to #1219

`filter` option doesn't work in getPastEvents('allEvents')
```ts 
const contract = new web3.eth.Contract(Basic.abi,contractAddress)
 const res = await contract.getPastEvents('allEvents',{
         fromBlock: 0,
         filter: {
             val: 12
         }
 })
```

#### Expected behavior
Should return filtered events.
documentation - [here](https://web3js.readthedocs.io/en/v1.8.2/web3-eth-contract.html#getpastevents)

#### Actual behavior
Do not filter events. Returns all of them.

### PR DESCRIPTION
**Pull request by avkos**
## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../blob/1.x/CONTRIBUTIONS.md).

Fixes #5862 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist for 1.x:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

## Checklist for 4.x:

- [ ] I have selected the correct 4.x base branch.
- [ ] Within the description, the feature or issue is discussed in detail or an issue is linked.   
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added any required tests for the changes I made 
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `yarn` successfully
- [ ] I ran `yarn lint` successfully
- [ ] I ran `yarn build:web` successfully
- [ ] I ran `yarn test:unit` successfully
- [ ] I ran `yarn test:integration` successfully
- [ ] I ran `compile:contracts` successfully
- [ ] I have tested my code.
- [ ] I have updated the corresponding `CHANGELOG.md` file in the packages I have edited.

### CODE REVIEW

**Review by luu-alex — APPROVED** [review]

File: packages/web3-eth-contract/src/index.js [hunk 1]
```diff
@@ -784,6 +783,24 @@ Contract.prototype._on = function(){
     return subscription;
 };
 
+const filterAllEventsResults = (subOptions, data) => {
```
Comment (Spacesai1or) [inline packages/web3-eth-contract/src/index.js:786]: You mentioned previously that this function didn't work 100% of the time, has that changed?

**Review by jdevcs — APPROVED** [review]

File: packages/web3-eth-contract/src/index.js (hunk 1 above)
Comment (avkos) [reply packages/web3-eth-contract/src/index.js:786]: This function works only for allEvents. Because we can’t filter events by topics when ‘allEvents’

**Review by Spacesai1or — APPROVED** [review]
