### PR TITLE
Local signing fixed

### LINKED ISSUE #1021: insufficient funds for gas * price + value
I have lots of Ether in the account and have tried various accounts.  
When I run this code below against testrpc, it completes successfully, but once I switch to my private geth or ropsten, this error shows consistently. 

My version of geth is 1.6.7

I use Ubuntu 16.04.

This below is the code portion of the code which I'm running taken from the web3 examples 

`var Web3 = require('web3');
var web3 = new Web3(
    new Web3.providers.HttpProvider('http://localhost:8545/')
);

var key="xxx"
var Tx = require('ethereumjs-tx');
var privateKey = new Buffer(key, 'hex')

var bytecode ="6060604052341561000c57fe5b5b60a68061001b6000396000f30060606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806339ec021c14603a575bfe5b3415604157fe5b6058600480803560ff16906020019091905050605a565b005b6000600082600a0a60ff16629896800262ffffff1691508190505b5050505600a165627a7a723058201aa083f84301acc104a3de0151822aa682702844181a821c16490689e05d729e0029";

var rawTx = {
    nonce: "0x2",    
    gasLimit: "0x2DC6C0",    
    gasPrice: "0x4A817C800",  
    value: '0x00', 
    data: '0x' + bytecode   
};

var tx = new Tx(rawTx);
tx.sign(privateKey);

var serializedTx = tx.serialize();

web3.eth.sendSignedTransaction( "0x" + serializedTx.toString('hex'))
.on('receipt', console.log);
`

Error shows like this.

Unhandled rejection Error: Returned error: insufficient funds for gas * price + value
    at Object.ErrorResponse (/home/bogdan/node_modules/web3/packages/web3-core-helpers/src/errors.js:29:16)
    at /home/bogdan/node_modules/web3/packages/web3-core-requestmanager/src/index.js:137:36
    at XMLHttpRequest.request.onreadystatechange (/home/bogdan/node_modules/web3/packages/web3-providers-http/src/index.js:64:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/bogdan/node_modules/web3/packages/web3-providers-http/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/bogdan/node_modules/web3/packages/web3-providers-http/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/bogdan/node_modules/web3/packages/web3-providers-http/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/home/bogdan/node_modules/web3/packages/web3-providers-http/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

### PR DESCRIPTION
**Pull request by nivida**
## Description

``ethereumjs-tx`` signing implemented.

Fixes #1021 #1517 #1074 #1169 #2033 #1793 #1126 #1134 #2578 #2569

## Type of change

- [x] Bug fix 

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no warnings.
- [x] I have updated or added types for all modules I've changed
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran ```npm run test``` in the root folder with success and extended the tests if necessary.
- [x] I ran ```npm run build``` in the root folder and tested it in the browser and with node.
- [x] I ran ```npm run dtslint``` in the root folder and tested that all my types are correct
- [x] I have tested my code on an ethereum test network.

### CODE REVIEW

File: packages/web3-core-method/src/methods/transaction/EthSendTransactionMethod.js [hunk 1]
```diff
@@ -153,7 +169,7 @@ export default class EthSendTransactionMethod extends SendTransactionMethod {
      * @returns {Boolean}
      */
     hasAccounts() {
-        return this.moduleInstance.accounts && this.moduleInstance.accounts.accountsIndex > 0;
+        return this.moduleInstance.accounts && this.moduleInstance.accounts.wallet.accountsIndex > 0;
```
Comment (wolovim) [inline packages/web3-core-method/src/methods/transaction/EthSendTransactionMethod.js:172]: Is there any opportunity for wallet to return `undefined` and break here?

File: packages/web3-eth-accounts/src/models/Account.js [hunk 2]
```diff
@@ -20,7 +20,7 @@
 import scryptsy from 'scrypt.js';
 import isString from 'lodash/isString';
 import isObject from 'lodash/isObject';
-import {fromPrivate, create, sign, decodeSignature} from 'eth-lib/lib/account'; // TODO: Remove this dependency
+import * as EthLibAccount from 'eth-lib/lib/account'; // TODO: Remove this dependency
```
Comment (wolovim) [inline packages/web3-eth-accounts/src/models/Account.js:23]: 👌 namespacing. Is this functionality redundant with ethereumjs-tx?

**Review by wolovim — COMMENTED** [review]
Coming in with little context, so just some surface-level feedback and clarifying questions:
1. ethereumjs-tx tidies up the TransactionSigner nicely 👌 
1. Is ethereumjs-tx a full replacement for eth-lib? I've wondered if eth-lib is "actively" maintained (last commit 1 yr ago).
1. Haven't looked into how you're packaging the lib or what support promises web3.js has made; just making sure this line in the ethereumjs-tx README is on your radar:
>Note: this package expects ECMAScript 6 (ES6) as a minimum environment. From browsers lacking ES6 support, please use a shim (like es6-shim) before including any of the builds from this repo.

File: packages/web3-eth-accounts/src/models/Account.js (hunk 2 above)
Comment (nivida) [reply packages/web3-eth-accounts/src/models/Account.js:23]: There is an ethereumjs package I could use to replace the eth-lib here too. But I will do this later because other enhancements have a higher priority. Thanks for the hint. I'll write it down on my checklist.

**Comment by nivida** [comment]
The es6-shim isn't required because of the babel polyfill I'm including. Thanks for your review! @marcgarreau
