### PR TITLE
fix: correctly close ws connection in web3-eth-contract integration tests

### LINKED ISSUE #7231: Web3-eth-contract tests update/fixes
--forceExit flag should be removed from the web3-eth-contract tests
test:integration

### PR DESCRIPTION
**Pull request by krzysu**
## Description

Correctly close ws connection in web3-eth-contract integration tests

Fixes #7231 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run lint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

### CODE REVIEW

File: scripts/system_tests_utils.ts [hunk 1]
```diff
@@ -165,7 +165,7 @@ export const closeOpenConnection = async (web3Context: Web3Context) => {
 		(web3Context.provider as unknown as Web3BaseProvider).disconnect();
 
 		await new Promise(resolve => {
-			setTimeout(resolve, 1000);
+			setTimeout(resolve, 1);
```
Comment (krzysu) [inline scripts/system_tests_utils.ts]: what was the idea behind waiting for 1s here? the more tests use this function to close connection, the longer the whole test suite will execute.

File: scripts/system_tests_utils.ts [hunk 2]
```diff
@@ -250,8 +250,9 @@ export const createNewAccount = async (config?: {
 			const url = getSystemTestProviderUrl();
 			const web3 = new Web3(url);
 			web3.registerPlugin(new HardhatPlugin());
+			// eslint-disable-next-line
 			await web3.hardhat.impersonateAccount(acc.address);
-			// await impersonateAccount(acc.address);
+			// eslint-disable-next-line
```
Comment (krzysu) [inline scripts/system_tests_utils.ts]: seems scripts are not eslinted till you modify them and then all previous issues come up (on git commit)

File: scripts/system_tests_utils.ts [hunk 3]
```diff
@@ -418,7 +425,7 @@ export const signAndSendContractMethodEIP2930 = async (
 
 export const createLocalAccount = async (web3: Web3) => {
 	const account = web3.eth.accounts.create();
-	await refillAccount((await createTempAccount()).address, account.address, '10000000000000000');
+	await refillAccount((await createTempAccount()).address, account.address, '100000000000000000');
```
Comment (krzysu) [inline scripts/system_tests_utils.ts:428]: increase refill amount as often tests are failing because of not enough funds

File: scripts/system_tests_utils.ts [hunk 4]
```diff
@@ -165,7 +165,8 @@ export const closeOpenConnection = async (web3Context: Web3Context) => {
 		(web3Context.provider as unknown as Web3BaseProvider).disconnect();
 
 		await new Promise(resolve => {
-			setTimeout(resolve, 1000);
```
Comment (krzysu) [inline scripts/system_tests_utils.ts:168]: why to wait for 1s on each `closeOpenConnection` close?

File: scripts/geth.sh [hunk 5]
```diff
@@ -12,16 +12,16 @@ start() {
...
 		echo "Waiting for geth..."
 		npx wait-port -t 10000 "$WEB3_SYSTEM_TEST_PORT"
-		echo "docker run -d -p 3333:3333 ethereum/client-go:v1.13.14-amd64 --nodiscover --nousb --ws --ws.addr 0.0.0.0 --ws.port 3333 --http --http.addr 0.0.0.0 --http.port 3334 --allow-insecure-unlock --http.api personal,web3,eth,admin,debug,txpool,net --ws.api personal,web3,eth,admin,debug,miner,txpool,net --dev"
-        docker run -d -p 3333:3333 ethereum/client-go:v1.13.14-amd64 --nodiscover --nousb --ws --ws.addr 0.0.0.0 --ws.port 3333 --http --http.addr 0.0.0.0 --http.port 3333 --allow-insecure-unlock --http.api personal,web3,eth,admin,debug,txpool,net --ws.api personal,web3,eth,admin,debug,miner,txpool,net --dev
+		echo "docker run -d -p 3333:3333 ethereum/client-go:v1.14.10-amd64 --nodiscover --nousb --ws --ws.addr 0.0.0.0 --ws.port 3333 --http --http.addr 0.0.0.0 --http.port 3334 --allow-insecure-unlock --http.api personal,web3,eth,admin,debug,txpool,net --ws.api personal,web3,eth,admin,debug,miner,txpool,net --dev"
```
Comment (krzysu) [inline scripts/geth.sh]: upgrade geth to the latest versioned amd64 release I found, shall we just use the latest tag (`client-go:latest-amd64`)? 
more: https://hub.docker.com/r/ethereum/client-go/tags

**Comment by krzysu** [comment]
With the upgraded version of Geth, some new errors have started to appear. For example, see: this build https://github.com/web3/web3.js/actions/runs/11702836716/job/32591923473
So I had to revert the geth version to the currently used one in the tests.

**Review by avkos — APPROVED** [review]

File: scripts/system_tests_utils.ts [hunk 6]
```diff
@@ -275,6 +277,7 @@ export const createNewAccount = async (config?: {
 			const url = getSystemTestProviderUrl();
 			const web3 = new Web3(url);
 			web3.registerPlugin(new HardhatPlugin());
+			// eslint-disable-next-line
```
Comment (jdevcs) [inline scripts/system_tests_utils.ts]: I'll suggest to specify and disable exact lint error

Comment (jdevcs) [reply scripts/system_tests_utils.ts]: and for above instances as well

File: scripts/system_tests_utils.ts (hunk 1 above)
Comment (jdevcs) [reply scripts/system_tests_utils.ts]: It was waiting for ws to reset and disconnect for random ws connection not closing in tests.

File: scripts/geth.sh (hunk 5 above)
Comment (jdevcs) [reply scripts/geth.sh]: yes , use latest.

**Comment by jdevcs** [comment]
> With the upgraded version of Geth, some new errors have started to appear. For example, see: this build https://github.com/web3/web3.js/actions/runs/11702836716/job/32591923473 So I had to revert the geth version to the currently used one in the tests.

pls see this in detail and open issue in geth,

**Comment by jdevcs** [comment]
PR looks good to me

File: scripts/geth.sh (hunk 5 above)
Comment (krzysu) [reply scripts/geth.sh]: issue created https://github.com/web3/web3.js/issues/7379
PR created https://github.com/web3/web3.js/pull/7380

File: scripts/system_tests_utils.ts (hunk 6 above)
Comment (krzysu) [reply scripts/system_tests_utils.ts]: done
