### PR TITLE
Fix staticPartLength calculation for multidimensional arrays.

### LINKED ISSUE #503: Incorrect value returned in tuple.
``` Solidity
contract test {
  function deeper() constant returns (byte[12][100] s, uint count) {
    count = 42;
    return (s, count);
  }
}
```

``` JavaScript
myContract.deeper((error, result) =>
  console.log(Number(result[1]))
)
```

`0` is printed instead of the expected `42`.

### PR DESCRIPTION
**Pull request by NodeGuy**
Fixes #503 and #521.

### CODE REVIEW

**Comment by frozeman** [comment]
Thanks so much for these fixes. Could you add some extra tests for those cases?

File: test/coder.decodeParam.js [hunk 1]
```diff
@@ -344,5 +344,34 @@ describe('lib/solidity/coder', function () {
...
+        test({ types: ['bytes1[2][1]', 'bool'], expected: [[['0xaa', '0xbb']], true],
+                                                            values: 'aa00000000000000000000000000000000000000000000000000000000000000' +
+                                                                    'bb00000000000000000000000000000000000000000000000000000000000000' +
+                                                                    '0000000000000000000000000000000000000000000000000000000000000001'});
+        test({ types: ['int[2][1]', 'bool'], expected: [[[new bn(1), new bn(2)]], true],
+                                                            values: '0000000000000000000000000000000000000000000000000000000000000001' +
+                                                                    '0000000000000000000000000000000000000000000000000000000000000002' +
+                                                                    '0000000000000000000000000000000000000000000000000000000000000001'});
+        test({ types: ['real[2][1]', 'bool'], expected: [[[new bn(1), new bn(2.125)]], true],
```
Comment (chriseth) [inline test/coder.decodeParam.js]: Note that the `real` types are deprecated.

**Comment by NodeGuy** [comment]
You're welcome.  From Monax with ❤️.
