### PR TITLE
fix: export Web3Account, Wallet and signature related types

### LINKED ISSUE #7341: Export all return types such as `Web3Account` or the signature type
Hi, I’ve noticed that some types returned by methods aren’t exported as types, such as `Web3Account` or `Signature` (`ReturnType<typeof account.sign>`). This makes it more difficult to structure larger TypeScript codebases effectively. Please see the example below:

```ts
// this is not possible
import { Signature, Web3Account } from "web3"

function processSignature(signature: Signature) {
  // Do something with the signature
}

function prepareAndSignTransaction(account: Web3Account, to: Address) {
  // Prepare the transaction
}
```

### PR DESCRIPTION
**Pull request by krzysu**
## Description

Export types that represent the return values of method calls but aren’t currently available as standalone types. Specifically, this includes `Web3Account`, `Wallet`, and signature-related types like `SignatureObject`, `SignResult`, and `SignTransactionResult`.

Fixes #7341

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run lint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

### CODE REVIEW

File: packages/web3-eth-accounts/src/types.ts [hunk 1]
```diff
@@ -16,38 +16,8 @@ along with web3.js.  If not, see <http://www.gnu.org/licenses/>.
...
-	s: string;
-	v: string;
-};
-
-export type SignTransactionResult = SignatureObject & {
-	rawTransaction: string;
-	transactionHash: string;
-};
-
-export type SignTransactionFunction = (
```
Comment (krzysu) [inline packages/web3-eth-accounts/src/types.ts:34]: this is not used anywhere

File: packages/web3-eth-accounts/src/types.ts [hunk 2]
```diff
@@ -16,38 +16,8 @@ along with web3.js.  If not, see <http://www.gnu.org/licenses/>.
...
-		| FeeMarketEIP1559TxData
-		| Record<string, unknown>,
-) => SignTransactionResult;
-
-export type SignResult = SignatureObject & {
-	message?: string;
-	signature: string;
-};
-
-export type SignFunction = (data: string, privateKey: string) => SignResult;
```
Comment (krzysu) [inline packages/web3-eth-accounts/src/types.ts:47]: this is not used anywhere

File: packages/web3/src/index.ts [hunk 3]
```diff
@@ -364,3 +364,4 @@ export * as validator from 'web3-validator';
  */
 export * from 'web3-errors';
 export * from 'web3-types';
+export type { Web3Account, Wallet } from 'web3-eth-accounts';
```
Comment (krzysu) [inline packages/web3/src/index.ts]: if there is any better place to export these, let me know!

File: packages/web3-eth-accounts/src/types.ts [hunk 4]
```diff
@@ -16,38 +16,8 @@ along with web3.js.  If not, see <http://www.gnu.org/licenses/>.
 */
 
 import { Web3BaseWalletAccount, HexString } from 'web3-types';
-import { FeeMarketEIP1559TxData, AccessListEIP2930TxData, TxData } from './tx/types.js';
 import { AccessListEIP2930Transaction, FeeMarketEIP1559Transaction, Transaction } from './tx';
 
-export type SignatureObject = {
```
Comment (jdevcs) [inline packages/web3-eth-accounts/src/types.ts:22]: I'll suggest to move only shared types that are used in 1+ packages in web3-types package, and for moved types re-export those from web3-eth-accounts package for backward compatibility.

File: packages/web3/src/index.ts (hunk 3 above)
Comment (jdevcs) [reply packages/web3/src/index.ts]: from web3-accts pkg

Comment (krzysu) [reply packages/web3/src/index.ts]: all account types are exported from `web3-eth-accounts` but not from `web3`. See https://github.com/web3/web3.js/blob/7341-export-types/packages/web3-eth-accounts/src/index.ts#L42
How to solve that?

File: packages/web3-eth-accounts/src/types.ts (hunk 4 above)
Comment (krzysu) [reply packages/web3-eth-accounts/src/types.ts:22]: the problem is that `SignatureObject` is used in web3-eth-accounts but is also part of the `Web3BaseWalletAccount` type in `web3-types`. 
See the type details below:

```ts
export interface Web3BaseWalletAccount {
	// ..
	readonly signTransaction: (tx: Transaction) => Promise<SignTransactionResult>;
	readonly sign: (data: Record<string, unknown> | string) => SignResult;
	//
}
```

Also, none of the `web3-eth-accounts` types are exported from the umbrella `web3` package, but I will reexport these for `web3-eth-accounts` backwards compatibility.

File: packages/web3/src/index.ts (hunk 3 above)
Comment (krzysu) [reply packages/web3/src/index.ts]: I moved the export of these to packages/web3/src/types.ts

**Review by luu-alex — APPROVED** [review]
