### PR TITLE
Fix for ABI encoding large negative ints

### LINKED ISSUE #5890: Negative large numbers throw exceptions when passed to encodeFunctionCall
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I pass a string representing a large number that is negative, for instance in the case of a int128:
2^128 / 2 - 1 = 170141183460469231731687303715884105727 * -1 = -170141183460469231731687303715884105727

I get this error:
Encode function call failed: invalid BigNumber string (argument="value", value="0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000-170141183460469231731687303715884105727", code=INVALID_ARGUMENT, version=bignumber/5.7.0)

After snooping through the repo, I found that you padStart int/uint values, which is okay for uints, but not for ints. (source: https://github.com/web3/web3.js/blob/1.x/packages/web3-eth-abi/src/index.js#L266-L274)

This behaviour doesn't occur for small ints, for instance -2, only large ones.

### Expected Behavior

Should be able to pass large negative numbers such as `-170141183460469231731687303715884105727`

### Steps to Reproduce

```ts
import Web3Abi from 'web3-eth-abi`;

const types = {
    "type": "function",
    "name": "pour",
    "inputs": [
        {
            "type": "bytes12",
            "name": "vaultId_"
        },
        {
            "type": "address",
            "name": "to"
        },
        {
            "type": "int128",
            "name": "ink"
        },
        {
            "type": "int128",
            "name": "art"
        }
    ]
};

const params = [
    "0x",
    "0x0000000000000000000000000000000000000000",
    "170141183460469231731687303715884105727",
    "-170141183460469231731687303715884105727"
]

const result = Web3Abi.encodeFunctionCall(types, params);

```

### Web3.js Version

1.8.2

### Environment

- Operating System: macOS Ventura 13.1
- Browser: Google Chrome 110.0.5481.177 (Official Build) (arm64) 
- Node.js Version: 14.19.-
- NPM Version: 6.14.16

### Anything Else?

_No response_

### PR DESCRIPTION
**Pull request by Spacesai1or**
closes #5890

### CODE REVIEW

**Review by luu-alex — APPROVED** [review]

File: packages/web3-eth-abi/src/index.js [hunk 1]
```diff
@@ -268,8 +268,13 @@ ABICoder.prototype.formatParam = function (type, param) {
...
         if (size / 8 < param.length) {
-            // pad to correct bit width
-            param = utils.leftPad(param, size);
+            if (param.startsWith('-')) {
+                // pad to correct bit width with - at the beginning
+                param = `-${utils.leftPad(param.substring(1), size)}`;
+            } else {
+                // pad to correct bit width
+                param = utils.leftPad(param, size);
+            }
```
Comment (spacesailor24) [inline packages/web3-eth-abi/src/index.js:277]: I based this branch off of #6238, so it includes all of those changes. The changes to this file are the only novel ones for this PR

File: packages/web3-eth-abi/src/index.js [hunk 2]
```diff
@@ -268,8 +268,11 @@ ABICoder.prototype.formatParam = function (type, param) {
     if (match) {
         let size = parseInt(match[2] || "256");
         if (size / 8 < param.length) {
-            // pad to correct bit width
-            param = utils.leftPad(param, size);
+            param = param.startsWith("-")
+                // pad to correct bit width, with - at the beginning
+                ? `-${utils.leftPad(param.substring(1), size)}`
+                // pad to correct bit width
+                : utils.leftPad(param, size);
```
Comment (spacesailor24) [inline packages/web3-eth-abi/src/index.js:275]: I based this branch off of #6238, so it includes all of those changes. The changes to this file are the only novel ones for this PR

**Review by avkos — APPROVED** [review]

**Review by jdevcs — APPROVED** [review]
