### PR TITLE
signTransaction fix

### LINKED ISSUE #4292: web3.eth.accounts.signTransaction returning invalid
#### Expected behavior
Should return correct v,r,s for `web3.eth.accounts.signTransaction`
#### Actual behavior
Always returning `  v: '0x00',
  r: '0x00000000000000000000',
  s: '0x00000000000000000000',`
#### Steps to reproduce the behavior

```
    const web3 = new Web3( 
        "https://mainnet.infura.io/v3/ID_OF_PROJ"
        );

    let data = await web3.eth.accounts.signTransaction({
        to: '0xF0109fC8DF283027b6285cc889F5aA624EaC1F55',
        value: '1000',
        gas: 21000,
    }, '0x0000000PRIVATEKEY');

    console.log(data)
```

#### Logs
`
{
  messageHash: '0x4bec55a14404b60aaf666effe60e67879d50072fd3a1312a76d5e9eeb7686d56',
  v: '0x00',
  r: '0x00000000000000000000',
  s: '0x00000000000000000000',
  rawTransaction: '0xf866808512bd61afdc82520894f0109fc8df283027b6285cc889f5aa624eac1f558203e88026a0a9fb8610d63edc53f11f8840f8b213ff677ffa22f3757c450ed48966e7699f0da06c39e77f71d7f969e899b4bb511931b461e635fde556394b1837ce946e99909f',
  transactionHash: '0xe8c2ffa6043bd43e096030ee4615c56514caf4e5debab5999ef62c168fdd0d20'
}`

#### Environment
"web3": "^1.5.2"

### PR DESCRIPTION
**Pull request by jdevcs**
## Description

Fixes #4292

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [x] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [x] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

File: packages/web3-eth-accounts/src/index.js [hunk 1]
```diff
@@ -228,9 +228,9 @@ Accounts.prototype.signTransaction = function signTransaction(tx, privateKey, ca
 
             var result = {
                 messageHash: '0x' + Buffer.from(signedTx.getMessageToSign(true)).toString('hex'),
-                v: '0x' + Buffer.from(signedTx.v).toString('hex'),
-                r: '0x' + Buffer.from(signedTx.r).toString('hex'),
-                s: '0x' + Buffer.from(signedTx.s).toString('hex'),
+                v: '0x' + signedTx.v.toString('hex'),
+                r: '0x' + signedTx.r.toString('hex'),
+                s: '0x' + signedTx.s.toString('hex'),
```
Comment (nazarhussain) [inline packages/web3-eth-accounts/src/index.js:233]: We have a function `web3.utils.toHex` in the utilities and we should be using it consistently across the codebase instead of manually encoding. 

https://web3js.readthedocs.io/en/v1.5.0/web3-utils.html#tohex

**Review by nazarhussain — CHANGES_REQUESTED** [review]

File: packages/web3-eth-accounts/src/index.js (hunk 1 above)
Comment (jdevcs) [reply packages/web3-eth-accounts/src/index.js:233]: I think toHex is Megamorphic and its not usually recommended to go in that direction as its not aligned with inline cache.

**Review by nazarhussain — DISMISSED** [review]

File: test/e2e.method.signing.js [hunk 2]
```diff
@@ -563,5 +564,43 @@ describe('transaction and message signing [ @E2E ]', function() {
...
+
+
+        const customCommon = {
+            baseChain: 'mainnet',
+            customChain: {
+                name: 'custom-network',
+                networkId: networkId,
+                chainId: chainId,
+            },
+            harfork: 'petersburg',
```
Comment (luu-alex) [inline test/e2e.method.signing.js]: should be `hardfork`?

Comment (jdevcs) [reply test/e2e.method.signing.js]: yes

Comment (Spacesai1or) [reply test/e2e.method.signing.js]:
```suggestion
            hardfork: 'petersburg',
```

**Review by Spacesai1or — APPROVED** [review]

**Review by luu-alex — APPROVED** [review]
