### PR TITLE
🏷️ Update AbstractProvider with correct typing

### LINKED ISSUE #5150: AbstractProvider interface has incorrect signature(s)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The `callback` parameter of the `sendAsync` method (and maybe the `send` method too) returns a promise (not sure if this is always the case.. but it returns a promise _sometimes_). The implementation does _not_ have a `void` signature.

https://github.com/ChainSafe/web3.js/blob/0b890b70b977451836dc693614960256bcbcb6d8/packages/web3-core/types/index.d.ts#L444-L449

### Expected Behavior

The `AbstractProvider` interface should be updated so that the `callback` parameter of `sendAsync` and `send` is correct.

`callback`'s return type should either be `unknown` or `Promise<unknown>` depending on whether promises are always returned.

### Steps to Reproduce

N/A

### Web3.js Version

1.7.3

### Environment

_No response_

### Anything Else?

_No response_

### PR DESCRIPTION
**Pull request by Dinatra**
## Description
Fix #5150

Improve [web3.js/packages/web3-core/types/index.d.ts](https://github.com/ChainSafe/web3.js/blob/0b890b70b977451836dc693614960256bcbcb6d8/packages/web3-core/types/index.d.ts#L444-L449) AbstractProvider interface, because the sendAsync & send callback dont return a void but sometimes it return a promise, like this usecase
```js
ethereum.send('eth_requestAccounts'): Promise<Array<string>>
```
by typing it as unknown, it may give some freedom to develop another provider around it instead of `Promise<unknown>`

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [x] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

File: packages/web3-core/types/index.d.ts [hunk 1]
```diff
@@ -442,8 +442,8 @@ export interface RequestArguments {
 }
 
 export interface AbstractProvider {
-    sendAsync(payload: JsonRpcPayload, callback: (error: Error | null, result?: JsonRpcResponse) => void): void;
-    send?(payload: JsonRpcPayload, callback: (error: Error | null, result?: JsonRpcResponse) => void): void;
+    sendAsync(payload: JsonRpcPayload, callback: (error: Error | null, result?: JsonRpcResponse) => unknown): void;
```
Comment (nazarhussain) [inline packages/web3-core/types/index.d.ts]:
```suggestion
    sendAsync(payload: JsonRpcPayload, callback?: (error: Error | null, result?: JsonRpcResponse) => Promise<any> | void): void;
```

**Review by nazarhussain — CHANGES_REQUESTED** [review]

**Comment by nazarhussain** [comment]
@kleimak Please add an entry to `CHANGELOG.md` as well.

**Comment by Dinatra** [comment]
Hi @nazarhussain 👋 
EDIT : I checked the recent PRs and followed their semantics, I added my entry under the tag `[1.7.4]` in the `Fixed` section 👍. Thanks for your reply ! can I add my entry under the `[1.7.5]` tag ?
like the following :
```
...
[Unreleased]
[1.7.5]
Fix[ISSUE-ID] "description"
```

File: CHANGELOG.md [hunk 2]
```diff
@@ -547,6 +547,7 @@ Released with 1.0.0-beta.37 code base.
 -  Fix bug in handleRevert logic for eth_sendRawTransaction (#4902)
 -  Fix resolve type of getBlock function (#4911)
 -  Web3-utils BN fix (#5132)
+-  Improving ``AbstractProvider`` interface (#5150)
```
Comment (nazarhussain) [inline CHANGELOG.md]: As `1.7.4` already released. This should actually go under `1.7.5` section.

**Review by nazarhussain — CHANGES_REQUESTED** [review]

File: CHANGELOG.md (hunk 2 above)
Comment (Dinatra) [reply CHANGELOG.md]: It's done ✅

**Review by nazarhussain — APPROVED** [review]

File: packages/web3-core/types/index.d.ts [hunk 3]
```diff
@@ -442,8 +442,8 @@ export interface RequestArguments {
 }
 
 export interface AbstractProvider {
-    sendAsync(payload: JsonRpcPayload, callback: (error: Error | null, result?: JsonRpcResponse) => void): void;
-    send?(payload: JsonRpcPayload, callback: (error: Error | null, result?: JsonRpcResponse) => void): void;
+    sendAsync(payload: JsonRpcPayload, callback?: (error: Error | null, result?: JsonRpcResponse) => Promise<any> | void): void;
```
Comment (janeklb) [inline packages/web3-core/types/index.d.ts]: Could this be typed as `Promise<unknown>`?

Comment (Dinatra) [reply packages/web3-core/types/index.d.ts]: It's updated ✅ 
And for request method, why do we let `any` as promise return type ? Isn't it better to put `unknown` too ? since conventionally it is advisable to put an `unknown` to a return value which will be assigned a new type in output, so we are obliged to assign a type to it in order to be able to use it contrary to any which allows any manipulation, it encourages good practice, doesn't it?

What do you think about it? 😄

**Review by jdevcs — APPROVED** [review]
@kleimak This PR LGTM, for full types support we are working on [web3.js 4.x](https://github.com/ChainSafe/web3.js/tree/4.x) so we will appreciate if you also have time for contributions in that.

**Comment by Dinatra** [comment]
@jdevcs 
Great, thanks for your approval. ✅ 

Of course, I would appreciate it 👍

File: packages/web3-core/types/index.d.ts (hunk 3 above)
Comment (janeklb) [reply packages/web3-core/types/index.d.ts]: I agree!  `unknown` is generally better than `any` (except for special cases, but i don't believe this to be one of them).

**Comment by janeklb** [comment]
> @kleimak This PR LGTM, for full types support we are working on [web3.js 4.x](https://github.com/ChainSafe/web3.js/tree/4.x) so we will appreciate if you also have time for contributions in that.

Just out of curiosity, what's happened with 2.x and 3.x?

File: packages/web3-core/types/index.d.ts (hunk 3 above)
Comment (Dinatra) [reply packages/web3-core/types/index.d.ts]: For my personal knowledge, can you explain me why ? 😄

Comment (janeklb) [reply packages/web3-core/types/index.d.ts]: I would defer to others who have explained it thoroughly and more eloquently than me -- for example:
- https://mainawycliffe.dev/blog/typescript-use-unknown-instead-of-any/
- https://www.benmvp.com/blog/when-use-typescript-unknown-versus-any/
- https://dev.to/tomdohnal/typescript-any-vs-unknown-a-deep-dive-3iem 

:)

Comment (Dinatra) [reply packages/web3-core/types/index.d.ts]: Thanks for sharing, I will take a look at it ;)

**Comment by jdevcs** [comment]
> > @kleimak This PR LGTM, for full types support we are working on [web3.js 4.x](https://github.com/ChainSafe/web3.js/tree/4.x) so we will appreciate if you also have time for contributions in that.
> 
> Just out of curiosity, what's happened with 2.x and 3.x?

https://github.com/ChainSafe/web3.js/blob/1.x/RELEASE.md#long-term-support-lts

2.x | Deprecated | 13. Jul. 2019 | 13. Jul. 2019 | 13. Jul. 2020
-- | -- | -- | -- | --
3.x | Deprecated | 9. Apr. 2021 | 9. Apr. 2021 | 26. Jan. 2022

**Review by nikoulai — APPROVED** [review]

**Review by avkos — APPROVED** [review]

**Comment by jdevcs** [comment]
Merged via https://github.com/ChainSafe/web3.js/pull/5206
