### PR TITLE
'0x' strings returned by contract are incorrectly interpreted as nulls

### LINKED ISSUE #4512: '0x' strings returned by contract are incorrectly interpreted as nulls
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

'0x' strings returned by contract are incorrectly interpreted as nulls

### Expected Behavior

They should be regular 2 chars length strings

### Steps to Reproduce

Consider following contract function

```solidity
function test() external view returns (string memory) {
    return '0x';
}
```
Now if we call it:

```js
const myContract = await MyContract.new();
expect(await myContract.test()).to.be.equal('0x');
```

We will see `AssertionError: expected null to equal '0x'`

### Web3.js Version

1.5.3

### Environment

- Operating System: Win10 x64
- Browser: All
- Node.js Version: v16.2.0
- NPM Version: 7.23.0

### Anything Else?

_No response_

### PR DESCRIPTION
**Pull request by nazarhussain**
## Description

Fix the encoding error for the string values. 

Fixes #4512

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:unit` with success.
- [x] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [x] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [x] I have tested my code on the live network.
- [x] I have checked the Deploy Preview and it looks correct.
- [x] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Review by luu-alex — APPROVED** [review]

File: test/abi.decodeParameter.js [hunk 1]
```diff
@@ -635,6 +635,9 @@ describe('lib/solidity/coder', function () {
                         '0000000000000000000000000000000000000000000000000000000000000060' +
                         '0000000000000000000000000000000000000000000000000000000000000006' +
                         '737472696e670000000000000000000000000000000000000000000000000000'})
+
+        test( { types: ['string'], expected: ["0x"],
+                values: '0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000023078000000000000000000000000000000000000000000000000000000000000'})
```
Comment (jdevcs) [inline test/abi.decodeParameter.js:640]: The change in code seems ok, but this test should decode '0x' in to '0x' string instead of `'0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000023078000000000000000000000000000000000000000000000000000000000000' `?

Comment (nazarhussain) [reply test/abi.decodeParameter.js:640]: Yes this test is exactly doing what is required.  Its binary value return from contract
> 0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000023078000000000000000000000000000000000000000000000000000000000000

to `"0x"` string.

**Review by jdevcs — APPROVED** [review]
