### PR TITLE
:building_construction: Improve system tests structure

### LINKED ISSUE #4998: Improve test system structure
We need an improved infrastructure for writing and running system tests. 

#### Expected behavior
The **integration** test that wrote are configured to be linted with **Jest**. So the same tests should run exactly in the browser environment to avoid duplicate effort of maintaining knowledge and code for double testing framework. 

#### Actual behavior

Currently system tests is configured with **Jasmine+Karma** which uses the **Mocha + Chai** under the hood. The expectations and DSL of the **Jest** does not work seamlessly with that setup.

### PR DESCRIPTION
**Pull request by nazarhussain**
## Description

Improve test structure. 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:unit` with success.
- [x] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [x] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [x] I have tested my code on the live network.
- [x] I have checked the Deploy Preview and it looks correct.
- [x] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

File: packages/web3-providers-http/test/fixtures/test_utils.ts [hunk 1]
```diff
@@ -0,0 +1 @@
+../../../../scripts/test_uitls.ts
```
Comment (luu-alex) [inline packages/web3-providers-http/test/fixtures/test_utils.ts]:
```suggestion
../../../../scripts/test_utils.ts
```

File: scripts/test_uitls.ts [hunk 2]
```diff
@@ -0,0 +1,12 @@
+export const getSystemTestAccounts = (): string[] =>
+	JSON.parse(process.env.WEB3_SYSTEM_TEST_ACCOUNTS ?? '[]') as string[];
+
+export const getSystemTestProvider = (): string => process.env.WEB3_SYSTEM_TEST_PROVIDER ?? '';
+
+export const getSystemTestPassword = (): string => process.env.WEB3_SYSTEM_TEST_PASSWORD ?? '';
```
Comment (luu-alex) [inline scripts/test_uitls.ts]: is this being used anywhere in the codebase? should the default `WEB3_SYSTEM_TEST_PASSWORD` be [this](https://github.com/ChainSafe/web3.js/pull/4949/files#diff-5a4957bc7903de70fcfb50dc6aa8851f9d16d84566568736af52e9e2df8c8628R3)?

Comment (nazarhussain) [reply scripts/test_uitls.ts]: It's used in the shell scripts to start ganache and geth.

File: package.json [hunk 3]
```diff
@@ -74,9 +79,10 @@
 		"ts-loader": "^9.2.8",
 		"ts-node": "^10.4.0",
 		"typescript": "^4.5.2",
+		"webpack": "^5.70.0",
+		"@chainsafe/geth-dev-assistant": "0.1.11",
```
Comment (jdevcs) [inline package.json]: Please make sure that there is no critical and no high vulnerabilities. Currently it have: **(3 high, 1 critical)**
It uses: 
```
minimist  <1.2.6 with
Severity: critical vulnerability 
```

**Review by jdevcs — CHANGES_REQUESTED** [review]

File: package.json [hunk 4]
```diff
@@ -34,18 +34,23 @@
...
-		"ganache-background": "yarn ganache > /dev/null & client=$! npx wait-port 8545",
-		"geth:build": "docker build ./.github -t gethnode -f .github/Dockerfile",
-		"geth": "docker run -p 8545:8545 gethnode --mine --miner.noverify --datadir data --networkid 4224 --nodiscover --nat \"any\" --ws --ws.addr 0.0.0.0 --ws.port 8545 --http --http.addr 0.0.0.0 --http.port 8545 --allow-insecure-unlock --http.api personal,web3,eth,admin,debug,miner,txpool,net --ws.api personal,web3,eth,admin,debug,miner,txpool,net --unlock 0 --password /pass",
-		"geth-background": "docker run -d -p 8545:8545 gethnode --mine --miner.noverify --datadir data --networkid 4224 --nodiscover --nat \"any\" --ws --ws.addr 0.0.0.0 --ws.port 8545 --http --http.addr 0.0.0.0 --http.port 8545 --allow-insecure-unlock --http.api personal,web3,eth,admin,debug,miner,txpool,net --ws.api personal,web3,eth,admin,debug,miner,txpool,net --unlock 0 --password /pass",
+		"ganache:start": "/bin/bash -c 'scripts/ganache.sh start'",
+		"ganache:stop": "./scripts/ganache.sh stop",
+		"geth:start": "/bin/bash -c 'scripts/geth.sh start'",
+		"geth:stop": "./scripts/geth.sh stop",
```
Comment (Spacesai1or) [inline package.json]: Regarding the use of `/bin/bash -c` [this](https://stackoverflow.com/a/16365367) is just something to be aware of, looks like we don't have much of an options since we're passing the `start` and `stop` commands

File: scripts/env.sh [hunk 5]
```diff
@@ -0,0 +1,7 @@
+export WEB3_SYSTEM_TEST_ENV=true
+export WEB3_SYSTEM_TEST_BACKEND=""
+export WEB3_SYSTEM_TEST_PASSWORD="smart guide what forget tired jungle always expire rescue boring glue champion"
```
Comment (Spacesai1or) [inline scripts/env.sh]: I would change this to `WEB3_SYSTEM_TEST_MNEMONIC` as there's a notion of a `password` for encrypting the private key, and this specific ENV is being used as a mnemonic phrase

File: scripts/ganache.sh [hunk 6]
```diff
@@ -0,0 +1,38 @@
...
+	source scripts/env.sh
+	WEB3_SYSTEM_TEST_BACKEND="ganache"
+
+	echo "Starting gancahe ..."
+	echo "npx ganache ethereum -m \"$WEB3_SYSTEM_TEST_PASSWORD\" -a 5 -p $WEB3_SYSTEM_TEST_HTTP_PORT &"
+	npx ganache ethereum -m "$WEB3_SYSTEM_TEST_PASSWORD" -a 5 -p $WEB3_SYSTEM_TEST_HTTP_PORT >/dev/null &
+
+	echo "Waiting for ganache..."
+	npx wait-port "$WEB3_SYSTEM_TEST_HTTP_PORT"
+	sleep 2
```
Comment (Spacesai1or) [inline scripts/ganache.sh]: Is this `sleep` necessary? Shouldn't `wait-port` be enough?

File: scripts/test_uitls.ts [hunk 7]
```diff
@@ -0,0 +1,12 @@
...
+
+export const itIf = (condition: (() => boolean) | boolean) =>
+	(typeof condition === 'function' ? condition() : condition) ? test : test.skip;
+
+export const describeIf = (condition: (() => boolean) | boolean) =>
+	(typeof condition === 'function' ? condition() : condition) ? describe : describe.skip;
```
Comment (Spacesai1or) [inline scripts/test_uitls.ts]: This is a neat idea!

File: scripts/test_uitls.ts (hunk 2 above)
Comment (Spacesai1or) [reply scripts/test_uitls.ts]: This specific function though doesn't seem to be called anywhere in this PR though

**Comment by Spacesai1or** [comment]
I think this looks great, thank you Nazar

File: scripts/ganache.sh (hunk 6 above)
Comment (nazarhussain) [reply scripts/ganache.sh]: Sometimes we have to wait for few ms to listen to events after sending a transaction.

File: package.json (hunk 4 above)
Comment (nazarhussain) [reply package.json]: It's because we are setting up ENV variables inside the script that requires to run it in a bash shell so change can be passed to next script.

File: package.json (hunk 3 above)
Comment (jdevcs) [reply package.json]: @spacesailor24 or @nazarhussain could one of you update and publish @chainsafe/geth-dev-assistant for removing this security issue, rest lgtm,

**Review by avkos — APPROVED** [review]
great work!

File: .github/workflows/build.yml [hunk 8]
```diff
@@ -1,70 +1,93 @@
...
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        node: [ 14, 16 ]
+        backend: ['geth', 'ganache']
+        mode: ['http', 'ws']
+    steps:
+      -   uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
```
Comment (Spacesai1or) [inline .github/workflows/build.yml]:
```suggestion
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
```

File: .github/workflows/build.yml [hunk 9]
```diff
@@ -1,70 +1,93 @@
...
+    needs: unit
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        node: [ 14, 16 ]
+        browser: ['electron', 'chrome', 'firefox']
+    steps:
+      -   uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
```
Comment (Spacesai1or) [inline .github/workflows/build.yml]:
```suggestion
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
```

File: .github/workflows/build.yml [hunk 10]
```diff
@@ -1,70 +1,93 @@
...
+      - run: yarn
 
-            -   if: (env.TEST_CMD == 'e2e_ganache')
-                run: yarn ganache-background && yarn test:integration
+  lint:
+    name: Lint
+    needs: build
+    runs-on: ubuntu-latest
+    env:
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
Comment (Spacesai1or) [inline .github/workflows/build.yml:31]: Curious as to why this is needed for the linter?

File: package.json [hunk 11]
```diff
@@ -34,17 +34,28 @@
...
 		"lint": "lerna run lint --stream --parallel",
 		"lint:fix": "lerna run lint:fix --stream --parallel",
 		"format": "lerna run format --stream --parallel",
 		"test": "lerna run test --stream --parallel",
 		"test:unit": "lerna run test:unit --stream --parallel",
 		"test:integration": "lerna run test:integration --stream",
-		"test:integration:browsers": "./node_modules/.bin/karma start karma.config.js",
+		"test:e2e:electron": "lerna run test:e2e:electron --stream",
+		"test:e2e:chrome": "lerna run test:e2e:chrome --stream",
+		"test:e2e:firefox": "lerna run test:e2e:firefox --stream",
```
Comment (Spacesai1or) [inline package.json]: Why don't these use `./scripts/test-runner.sh`?

File: package.json [hunk 12]
```diff
@@ -34,17 +34,28 @@
...
+		"test:e2e:ganache:http": "./scripts/test-runner.sh ganache http",
+		"test:e2e:ganache:ws": "./scripts/test-runner.sh ganache ws",
+		"test:e2e:geth:http": "./scripts/test-runner.sh geth http",
+		"test:e2e:geth:ws": "./scripts/test-runner.sh geth ws",
+		"test:e2e:browsers:electron": "./scripts/test-runner.sh ganache ws electron",
+		"test:e2e:browsers:chrome": "./scripts/test-runner.sh ganache ws chrome",
+		"test:e2e:browsers:firefox": "./scripts/test-runner.sh ganache ws firefox",
```
Comment (Spacesai1or) [inline package.json]: What the difference between these tests from:

```json
"test:e2e:electron": "lerna run test:e2e:electron --stream",
"test:e2e:chrome": "lerna run test:e2e:chrome --stream",
"test:e2e:firefox": "lerna run test:e2e:firefox --stream",
```

Shouldn't they be called

```json
"test:e2e:electron:ws"
"test:e2e:chrome:ws"
"test:e2e:firefox:ws"
```

and shouldn't there be the `http` variants?

File: package.json [hunk 13]
```diff
@@ -55,28 +66,23 @@
 		"buffer": "^6.0.3",
 		"bufferutil": "^4.0.6",
 		"crypto-browserify": "^3.12.0",
+		"cypress": "^9.6.0",
+		"cypress-jest-adapter": "^0.1.1",
```
Comment (Spacesai1or) [inline package.json:67]: My concern with using this helper package (`cypress-jest-adapter`) is that it may not be actively maintained

image

So if we plan to use it, we may need to maintain it ourselves. Even the dependencies haven't been upgraded in over a year:

image

File: packages/web3-eth/test/integration/unsubscribe.test.ts [hunk 14]
```diff
@@ -18,14 +18,14 @@ import WebSocketProvider from 'web3-providers-ws/dist';
 import { SupportedProviders } from 'web3-core';
 import Web3Eth from '../../src/index';
 import { NewHeadsSubscription, SyncingSubscription } from '../../src/web3_subscriptions';
-import { clientWsUrl } from '../../../../.github/test.config'; // eslint-disable-line import/no-relative-packages
+import { getSystemTestProvider, describeIf } from '../fixtures/system_test_utils'; // eslint-disable-line import/no-relative-packages
```
Comment (Spacesai1or) [inline packages/web3-eth/test/integration/unsubscribe.test.ts]:
```suggestion
import { getSystemTestProvider, describeIf } from '../fixtures/system_test_utils';
```

Based off other changes, disabling the linter here isn't needed?

File: packages/web3-utils/test/fixtures/converters.ts [hunk 15]
```diff
@@ -71,7 +71,6 @@ export const numberToHexValidData: [Numbers, HexString][] = [
 	[256, '0x100'],
 	[54, '0x36'],
 	[BigInt(12), '0xc'],
-	[12n, '0xc'],
```
Comment (Spacesai1or) [inline packages/web3-utils/test/fixtures/converters.ts]: Why were these test cases removed?

File: packages/web3-utils/test/fixtures/string_manipulation.ts [hunk 16]
```diff
@@ -27,8 +27,6 @@ export const padLeftData: [[Numbers, number, string], HexString][] = [
 	[['-abcd', 8, '0'], '000-abcd'],
 	[[BigInt('9007199254740992'), 32, '0'], '0x00000000000000000020000000000000'],
 	[[BigInt('-9007199254740992'), 32, '0'], '-0x00000000000000000020000000000000'],
-	[[9007199254740992n, 32, '0'], '0x00000000000000000020000000000000'],
```
Comment (Spacesai1or) [inline packages/web3-utils/test/fixtures/string_manipulation.ts]: Why were these test cases removed?

File: packages/web3-utils/test/fixtures/validation.ts [hunk 17]
```diff
@@ -24,7 +24,7 @@ export const compareBlockNumbersValidData: [[Numbers, Numbers], number][] = [
 	[[2, 1], 1],
 	[[BigInt(1), BigInt(1)], 0],
 	[[BigInt(1), BigInt(2)], -1],
-	[[BigInt(2), 1n], 1],
```
Comment (Spacesai1or) [inline packages/web3-utils/test/fixtures/validation.ts]: This notation for BigInts should be valid and tested, no?

File: packages/web3-validator/test/fixtures/validation.ts [hunk 18]
```diff
@@ -131,8 +131,7 @@ export const invalidHexStrictData: any[] = [
 	'0',
 	1,
 	BigInt(12),
-	12n,
-	-255n,
```
Comment (Spacesai1or) [inline packages/web3-validator/test/fixtures/validation.ts]: This notation for BigInts should be valid and tested, no?

File: scripts/system_tests_utils.ts [hunk 19]
```diff
@@ -0,0 +1,105 @@
...
+		privateKey: '0x34aeb1f338c17e6b440c189655c89fcef148893a24a7f15c0cb666d9cf5eacb3',
+	},
+];
+
+export const getSystemTestAccounts = async (): Promise<string[]> => {
+	if (_accounts.length > 0) {
+		return _accounts;
+	}
+
+	const clientUrl = `http://localhost:${process.env.WEB3_SYSTEM_TEST_PORT ?? 8545}`;
```
Comment (Spacesai1or) [inline scripts/system_tests_utils.ts]: Shouldn't this call `getSystemTestProvider`? In case the host is not `localhost`

**Review by avkos — APPROVED** [review]
Looks great. just need to answer [spacesailor24](https://github.com/spacesailor24) questions

File: .github/workflows/build.yml (hunk 10 above)
Comment (nazarhussain) [reply .github/workflows/build.yml:31]: I personally dont' know. I believe it was copied over from previous configurations.

File: package.json (hunk 11 above)
Comment (nazarhussain) [reply package.json]: These are used inside `./scripts/test-runner.sh`, I added these separately to help run separate tasks manually during the development.

File: package.json (hunk 12 above)
Comment (nazarhussain) [reply package.json]: Yes we can rename these tasks. The earlier pipeline was configured only for the `ws` on the browsers, so I used it same. I think as we already run the tests separately in integration for both `http` and `ws`, for browsers just the `ws` would be good enough.

File: package.json (hunk 13 above)
Comment (nazarhussain) [reply package.json:67]: Yes it's not been updated because the the Jest API is not updated since long time and it's just the DSL wrapper on top of it.

Comment (nazarhussain) [reply package.json:67]: For dependencies, we may fork and update those. But since it's just the development dependency, I believe it's fine to use.

File: packages/web3-utils/test/fixtures/converters.ts (hunk 15 above)
Comment (nazarhussain) [reply packages/web3-utils/test/fixtures/converters.ts]: These are duplicated with `[BigInt(12), '0xc']`.

The Cypress is preconfigured with `es2019` TS target. We were using `es2020` earlier. The only difference related to our codebase is that BigInt literal values are not supported in `es2019`.

File: packages/web3-utils/test/fixtures/string_manipulation.ts (hunk 16 above)
Comment (nazarhussain) [reply packages/web3-utils/test/fixtures/string_manipulation.ts]: Same as replied above.

File: packages/web3-utils/test/fixtures/validation.ts (hunk 17 above)
Comment (nazarhussain) [reply packages/web3-utils/test/fixtures/validation.ts]: Replied above.

**Review by luu-alex — APPROVED** [review]

**Review by nikoulai — APPROVED** [review]

**Review by Spacesai1or — APPROVED** [review]

File: .github/workflows/build.yml (hunk 10 above)
Comment (Spacesai1or) [reply .github/workflows/build.yml:31]: I think we should try removing it, probably necessary for something in 1.x, but I don't think it's needed for 4.x

File: package.json (hunk 13 above)
Comment (Spacesai1or) [reply package.json:67]: Created an [issue](https://github.com/ChainSafe/web3.js/issues/5002) to track this

**Review by jdevcs — APPROVED** [review]
