### PR TITLE
fix(web3-errors): the undefined data in Eip838ExecutionError

### LINKED ISSUE #6433: TypeError: Cannot use 'in' operator to search for 'originalError' in null
#### Expected behavior
Throwing error with message that my transaction/gas estimating was reverted

#### Actual behavior

\web3-errors\src\errors\contract_errors.ts:163 line throws next error:
```
 if ('originalError' in error.data) {
TypeError: Cannot use 'in' operator to search for 'originalError' in null
```

It can be thrown by web3.eth..estimateGas() or w3.eth.sendSignedTransaction().

My transaction was reverted and I just logged it in console (in library code) to understand what happened. Error object is: 
```
{
  "code": -32000,
  "message": "execution reverted",
  "data": null
}
```
As soon as `typeof null === 'object'` is true web3-errors library throws an error above in this code:
```
if (typeof error.data === 'object') {
            let originalError;
            if ('originalError' in error.data) {
```
Error throwed in `web3-errors\src\errors\contract_errors.ts:163`

#### Steps to reproduce the behavior

I don't actually know why transaction is reverted. Code throws it randomly. 

#### Logs

```
root\node_modules\web3-errors\src\errors\contract_errors.ts:163
                        if ('originalError' in error.data) {
                    ^
TypeError: Cannot use 'in' operator to search for 'originalError' in null
    at new Eip838ExecutionError (root\node_modules\web3-errors\src\errors\contract_errors.ts:163:21)
    at new ContractExecutionError (root\node_modules\web3-errors\src\errors\contract_errors.ts:225:3)
    at Function._isReverted (root\node_modules\web3-core\src\web3_request_manager.ts:432:48)
    at Web3RequestManager._processJsonRpcResponse (root\node_modules\web3-core\src\web3_request_manager.ts:361:35)
    at Web3RequestManager.<anonymous> (root\node_modules\web3-core\src\web3_request_manager.ts:206:16)
    at Generator.next (<anonymous>)
    at fulfilled (root\node_modules\web3-core\lib\commonjs\web3_request_manager.js:21:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

#### Environment
npm - 9.8.1
node - 18.17.1
web3 - 4.1.1
OS - Windows 10

### PR DESCRIPTION
**Pull request by Alfxjx**
## Description

Fixes #6433 

process the undefined data in Eip838ExecutionError constructor to avoid an "read something from undefined" bug.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run lint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:unit` with success.
- [x] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [x] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [x] I have linked Issue(s) with this PR in "Linked Issues" menu.

### CODE REVIEW

**Review by avkos — APPROVED** [review]

File: packages/web3-errors/src/errors/contract_errors.ts [hunk 1]
```diff
@@ -159,7 +159,7 @@ export class Eip838ExecutionError extends Web3ContractError {
 		//	 error.data, error.data.data or error.data.originalError.data (https://github.com/web3/web3.js/issues/4454#issuecomment-1485953455)
 		if (typeof error.data === 'object') {
 			let originalError: { data: string };
-			if ('originalError' in error.data) {
+			if (error.data && 'originalError' in error.data) {
```
Comment (jdevcs) [inline packages/web3-errors/src/errors/contract_errors.ts:162]: @Alfxjx Thanks, also add changelog with issue #, in :
https://github.com/web3/web3.js/blob/4.x/packages/web3-errors/CHANGELOG.md of your branch

Comment (Alfxjx) [reply packages/web3-errors/src/errors/contract_errors.ts:162]: Thank you for your comments, I submitted the changelog, is it right or should I update the version in package.json of web3-errors

Comment (Muhammad-Altabba) [reply packages/web3-errors/src/errors/contract_errors.ts:162]: Thanks @Alfxjx ,
No need to update the version. We do the version update later in a separate PR.

File: packages/web3-errors/test/unit/__snapshots__/errors.test.ts.snap [hunk 2]
```diff
@@ -156,6 +156,17 @@ exports[`errors Eip838ExecutionError should get the data from error.data.origina
 }
 `;
 
+exports[`errors Eip838ExecutionError should return correctly when data is undefined 1`] = `
+{
+  "cause": undefined,
+  "code": undefined,
+  "data": undefined,
```
Comment (Muhammad-Altabba) [inline packages/web3-errors/test/unit/__snapshots__/errors.test.ts.snap:163]: The code was already working when `data` is `undefined`. But it does not work when data is `null`. So, could you please update the tests?
Thanks,

**Review by Muhammad-Altabba — CHANGES_REQUESTED** [review]

File: packages/web3-errors/test/unit/__snapshots__/errors.test.ts.snap (hunk 2 above)
Comment (Alfxjx) [reply packages/web3-errors/test/unit/__snapshots__/errors.test.ts.snap:163]: ok I will look into it and fix.

Comment (Muhammad-Altabba) [reply packages/web3-errors/test/unit/__snapshots__/errors.test.ts.snap:163]: Hi @Alfxjx ,
Just to clarify that your code looks great! And what I proposed to update is only your tests. That is to test with `null` instead of `undefined`. Please, let me know if you need any help to finish this.
Thanks,

**Comment by jdevcs** [comment]
@Muhammad-Altabba could you update changelog and merge this PR, as seems @Alfxjx is away.

**Comment by jdevcs** [comment]
cc: @mconnelly8

**Comment by jdevcs** [comment]
this PR will be merged into 4.x via: [web3:junaid/eip838fix](https://github.com/web3/web3.js/tree/junaid/eip838fix)

**Review by ghost — COMMENTED** [review]
Julita Barelkowska

**Review by ghost — COMMENTED** [review]
...

**Review by ghost — COMMENTED** [review]
🤗

**Review by ghost — COMMENTED** [review]
👍
