### PR TITLE
Fix Contract methods input param type any[]

### LINKED ISSUE #7302: Contract methods have parameters with the type `any[]`
#### Expected behavior
Contract methods have typed parameters.

#### Actual behavior
Contract methods have parameters with the type `any[]`.

#### Steps to reproduce the behavior
```ts
import Web3 from "web3";

const abi = [{
  inputs: [
    { internalType: "uint256", name: "testArg1", type: "uint256" },
    { internalType: "uint256", name: "testArg2", type: "uint256" },
  ],
  name: "test",
  outputs: [{ internalType: "uint256", name: "testRes1", type: "uint256" }],
  stateMutability: "nonpayable",
  type: "function",
}] as const;

const web3 = new Web3();
const contract = new web3.eth.Contract(abi);

// Actual: No error occurs here.
// Expected: Error - Expected 2 arguments, but got 0
contract.methods.test();

// Actual: any[]
// Expected: [MatchPrimitiveType<"uint256", unknown>, MatchPrimitiveType<"uint256", unknown>]
type Params = Parameters<typeof contract['methods']['test']>;
```

#### Solution
https://github.com/web3/web3.js/blob/dcd9d6a0803ad232003cb7e935057711c5b7e381/packages/web3-eth-contract/src/contract.ts#L131
Should be changed to `extends never` or something similar. Since everything is extending type `unknown`.

#### Environment

```
web3: 4.13.0
typescript: 5.6.2
```

### PR DESCRIPTION
**Pull request by avkos**
## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](https://github.com/web3/web3.js/blob/4.x/.github/CONTRIBUTING.md).

Fixes #7302

Behavior right now

```ts
const abiAsConst = [
			{
				inputs: [
					{ internalType: 'uint256', name: 'testArg1', type: 'uint256' },
					{ internalType: 'uint256', name: 'testArg2', type: 'uint256' },
				],
				name: 'testWithParams',
				outputs: [{ internalType: 'uint256', name: 'testRes1', type: 'uint256' }],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [],
				name: 'testWithoutParams',
				outputs: [{ internalType: 'uint256', name: 'testRes1', type: 'uint256' }],
				stateMutability: 'nonpayable',
				type: 'function',
			},
		] as const;

		const abiAsArray = [
			{
				inputs: [
					{ internalType: 'uint256', name: 'testArg1', type: 'uint256' },
					{ internalType: 'uint256', name: 'testArg2', type: 'uint256' },
				],
				name: 'testWithParams',
				outputs: [{ internalType: 'uint256', name: 'testRes1', type: 'uint256' }],
				stateMutability: 'nonpayable',
				type: 'function',
			},
			{
				inputs: [],
				name: 'testWithoutParams',
				outputs: [{ internalType: 'uint256', name: 'testRes1', type: 'uint256' }],
				stateMutability: 'nonpayable',
				type: 'function',
			},
		];
```

image

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run lint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

### CODE REVIEW

**Review by jdevcs — APPROVED** [review]

**Review by jdevcs — COMMENTED** [review]
plus check failing tests

File: packages/web3-eth-contract/src/contract.ts [hunk 1]
```diff
@@ -130,7 +130,11 @@ type ContractBoundMethod<
 	Abi extends AbiFunctionFragment,
 	Method extends ContractMethod<Abi> = ContractMethod<Abi>,
 > = (
-	...args: Method['Inputs'] extends undefined | unknown ? any[] : Method['Inputs']
+	...args: Abi extends undefined
+		? any[]
+		: Method['Inputs'] extends never
+		? any[]
+		: Method['Inputs']
```
Comment (Muhammad-Altabba) [inline packages/web3-eth-contract/src/contract.ts:137]: This suggestion is exactly the same but avoid nested trinary:
```suggestion
	...args: Method['Inputs'] extends undefined | never ? any[] : Method['Inputs']
```

**Review by Muhammad-Altabba — APPROVED** [review]
All sounds great!
Just a tiny suggestion.

File: packages/web3-eth-contract/src/contract.ts (hunk 1 above)
Comment (avkos) [reply packages/web3-eth-contract/src/contract.ts:137]: it will not work.. as you see first param is Abi  `Abi extends undefined` and second one Method['Inputs'] `Method['Inputs'] extends never`
