### PR TITLE
Web3RequestManager is not compatible with the Ganache provider

### LINKED ISSUE #5288: Web3RequestManager is not compatible with the Ganache provider
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is method `createInterfaceAdapter` in `truffle` which proxies the `web3` adapter to different adapter. 

https://github.com/trufflesuite/truffle/blob/c5de9c238aa07f7a9bed701fa83bab3457011f3b/packages/interface-adapter/lib/adapter/index.ts#L14

Here is a sample code which is creating `proxy` object for the `Ganache` adapter. 

https://github.com/trufflesuite/truffle/blob/c5de9c238aa07f7a9bed701fa83bab3457011f3b/packages/interface-adapter/test/quorum-getBlock.test.ts#L16-L28

Our request manager could not identify the right adapter type for the adapter and hang the request forever. 

### Expected Behavior

Ganache should work fine with the web3 request manager. 

### Steps to Reproduce

Mentioned above. 

### Web3.js Version

4.x

### Environment

- Operating System: N/A
- Browser: N/A
- Node.js Version: 16.x
- NPM Version: N/A

### Anything Else?

The below logic assumes that the provider which have `request` method should accept a callback. But it seems that ganache provider does not accept a callback rather return a promise. 

https://github.com/ChainSafe/web3.js/blob/0b903378be4cee0f2a9dc2c0572ffcbce5e97afd/packages/web3-core/src/web3_request_manager.ts#L176-L178

### PR DESCRIPTION
**Pull request by nazarhussain**
## Description

Fixes #5288

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [x] I ran `npm run build` with success.
- [x] I have tested the built `dist/web3.min.js` in a browser.
- [x] I have tested my code on the live network.
- [x] I have checked the Deploy Preview and it looks correct.
- [x] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Review by avkos — APPROVED** [review]

File: packages/web3-core/src/web3_request_manager.ts [hunk 1]
```diff
@@ -219,42 +272,80 @@ export class Web3RequestManager<
...
-			if (response.id && payload.id !== response.id) {
-				throw new InvalidResponseError<ErrorType>(response);
+			const res = {
+				jsonrpc: '2.0',
+				// eslint-disable-next-line no-nested-ternary
+				id: jsonRpc.isBatchRequest(payload)
+					? payload[0].id
+					: 'id' in payload
+					? payload.id
+					: 'NON_EXISTING_ID',
```
Comment (jdevcs) [inline packages/web3-core/src/web3_request_manager.ts]: If there was an error in detecting the id in the Request object, it MUST be Null. instead of NON_EXISTING_ID 
 https://www.jsonrpc.org/specification

File: packages/web3-core/src/web3_request_manager.ts [hunk 2]
```diff
@@ -219,42 +272,80 @@ export class Web3RequestManager<
 	private _processJsonRpcResponse<ResultType, ErrorType, RequestType>(
 		payload: JsonRpcPayload<RequestType>,
 		response: JsonRpcResponse<ResultType, ErrorType>,
+		{ legacy, error }: { legacy: boolean; error: boolean },
```
Comment (jdevcs) [inline packages/web3-core/src/web3_request_manager.ts:275]: can you create a type for `{ legacy: boolean; error: boolean }` and use that in this PR. It will be more clean.

**Review by jdevcs — CHANGES_REQUESTED** [review]

File: packages/web3-core/src/web3_request_manager.ts (hunk 1 above)
Comment (nazarhussain) [reply packages/web3-core/src/web3_request_manager.ts]: https://www.jsonrpc.org/specification#id1
> The use of Null as a value for the id member in a Request object is discouraged, because this specification uses a value of Null for Responses with an unknown id. Also, because JSON-RPC 1.0 uses an id value of Null for Notifications this could cause confusion in handling.


This case is only for the legacy implementations which don't follow fully compliance JSON-RPC specification. If we use `null` the upper level code will fail as it checks the valid response must contains some id.

File: packages/web3-core/src/web3_request_manager.ts (hunk 2 above)
Comment (nazarhussain) [reply packages/web3-core/src/web3_request_manager.ts:275]: This type is created and used only here. So seems fine to just keep inline.

File: packages/web3-core/src/web3_request_manager.ts (hunk 1 above)
Comment (jdevcs) [reply packages/web3-core/src/web3_request_manager.ts]: [link you mentioned above ](https://www.jsonrpc.org/specification#id1) is for request object. and object under discussion is response. ( last line ) 

image

If upper level code in our lib always expects some id thn it should always put id in request obj for getting it in response.

**Comment by nazarhussain** [comment]
@jdevcs Please review.

**Review by jdevcs — APPROVED** [review]

File: packages/web3-core/test/unit/web3_request_manager.test.ts [hunk 3]
```diff
@@ -641,12 +739,68 @@ describe('Web3RequestManager', () => {
 			});
 		});
 
+		describe('eip15593-provider', () => {
+			beforeEach(() => {
+				jest.spyOn(utils, 'isWeb3Provider').mockReturnValue(false);
+				jest.spyOn(utils, 'isLegacyRequestProvider').mockReturnValue(false);
+				jest.spyOn(utils, 'isLegacySendProvider').mockReturnValue(false);
+				jest.spyOn(utils, 'isLegacySendAsyncProvider').mockReturnValue(false);
```
Comment (Muhammad-Altabba) [inline packages/web3-core/test/unit/web3_request_manager.test.ts]: Why sping on all those providers while the test case is just for `eip15593`?

File: packages/web3-core/src/web3_request_manager.ts [hunk 4]
```diff
@@ -169,28 +171,66 @@ export class Web3RequestManager<
 				response = error as JsonRpcResponse<ResponseType>;
 			}
 
-			return this._processJsonRpcResponse(payload, response);
+			return this._processJsonRpcResponse(payload, response, { legacy: false, error: false });
+		}
+
+		if (isEIP1193Provider(provider)) {
```
Comment (Muhammad-Altabba) [inline packages/web3-core/src/web3_request_manager.ts:177]: I think we need later to consider refactoring to put the difference between every provider inside the provider class. So, we would not have to handle the differences in if statements.

**Review by Muhammad-Altabba — APPROVED** [review]
Looks good. I just have one discussion point and one question.

File: packages/web3-core/test/unit/web3_request_manager.test.ts (hunk 3 above)
Comment (Spacesai1or) [inline packages/web3-core/test/unit/web3_request_manager.test.ts]:
```suggestion
```
I removed these locally and the tests still pass

File: packages/web3-core/test/unit/web3_request_manager.test.ts [hunk 5]
```diff
@@ -379,6 +380,103 @@ describe('Web3RequestManager', () => {
...
```
Comment (Spacesai1or) [inline packages/web3-core/test/unit/web3_request_manager.test.ts:388]:
```suggestion
```
I removed these locally and the tests still pass

File: packages/web3-core/test/unit/web3_request_manager.test.ts [hunk 6]
```diff
@@ -641,12 +739,68 @@ describe('Web3RequestManager', () => {
 			});
 		});
 
+		describe('eip15593-provider', () => {
```
Comment (Spacesai1or) [inline packages/web3-core/test/unit/web3_request_manager.test.ts]:
```suggestion
		describe('eip1193-provider', () => {
```

File: packages/web3-core/test/unit/web3_request_manager.test.ts [hunk 7]
```diff
@@ -379,6 +380,103 @@ describe('Web3RequestManager', () => {
...
```
Comment (Spacesai1or) [inline packages/web3-core/test/unit/web3_request_manager.test.ts]:
```suggestion
		describe('eip1193-provider', () => {
```

File: packages/web3-core/test/unit/web3_request_manager.test.ts [hunk 8]
```diff
@@ -379,6 +380,103 @@ describe('Web3RequestManager', () => {
...
+
+				await expect(manager.send(request)).rejects.toThrow(
+					new InvalidResponseError(errorResponse),
+				);
+				expect(myProvider.request).toHaveBeenCalledTimes(1);
+				expect(myProvider.request).toHaveBeenCalledWith(payload);
+			});
+		});
+
+		describe('eip15593-provider - return non json-rpc compliance response', () => {
```
Comment (Spacesai1or) [inline packages/web3-core/test/unit/web3_request_manager.test.ts]:
```suggestion
		describe('eip1193-provider - return non json-rpc compliance response', () => {
```

File: packages/web3-core/test/unit/web3_request_manager.test.ts [hunk 9]
```diff
@@ -379,6 +380,103 @@ describe('Web3RequestManager', () => {
...
+			beforeEach(() => {
+				jest.spyOn(utils, 'isWeb3Provider').mockReturnValue(false);
+				jest.spyOn(utils, 'isLegacyRequestProvider').mockReturnValue(false);
+				jest.spyOn(utils, 'isLegacySendProvider').mockReturnValue(false);
+				jest.spyOn(utils, 'isLegacySendAsyncProvider').mockReturnValue(false);
```
Comment (Spacesai1or) [inline packages/web3-core/test/unit/web3_request_manager.test.ts:445]:
```suggestion
```
I removed these locally and the tests still pass

File: packages/web3-core/test/unit/web3_request_manager.test.ts [hunk 10]
```diff
@@ -379,6 +380,103 @@ describe('Web3RequestManager', () => {
...
+		describe('eip15593-provider', () => {
+			beforeEach(() => {
+				jest.spyOn(utils, 'isWeb3Provider').mockReturnValue(false);
+				jest.spyOn(utils, 'isLegacyRequestProvider').mockReturnValue(false);
+				jest.spyOn(utils, 'isLegacySendProvider').mockReturnValue(false);
+				jest.spyOn(utils, 'isLegacySendAsyncProvider').mockReturnValue(false);
+				jest.spyOn(utils, 'isEIP1193Provider').mockReturnValue(true);
+			});
+
+			it('should pass request to provider and resolve if provider resolves it', async () => {
```
Comment (jdevcs) [inline packages/web3-core/test/unit/web3_request_manager.test.ts:392]: We should also have some [system tests](https://github.com/ChainSafe/web3.js/issues/5309), and we can plan that for release after alpha.

File: packages/web3-core/test/unit/web3_request_manager.test.ts (hunk 3 above)
Comment (nazarhussain) [reply packages/web3-core/test/unit/web3_request_manager.test.ts]: To make sure we the only code branch regarding `eip15593` is executed.

File: packages/web3-core/src/web3_request_manager.ts (hunk 4 above)
Comment (nazarhussain) [reply packages/web3-core/src/web3_request_manager.ts:177]: Yes a lot can be refactored but most of that will be deprecated soon anyway.

**Comment by nazarhussain** [comment]
@spacesailor24 I resolved all your feedback. Merging this PR.
