### PR TITLE
Fix 3380: Add AbstractProvider

### LINKED ISSUE #3380: Web3 constructor does not accept custom/non-standard providers in TypeScript
#### Overview

Related to https://github.com/ethereum/web3.js/issues/2266

There should be a way to overload the TypeScript definition of `Web3` constructor to accept custom providers. I've tried everything, even [declaration merging](https://github.com/Microsoft/TypeScript/issues/14080) won't work. The easiest solution I foresee, which would not be a breaking change, is to provide a basic `Provider` interface which all providers must implement. Using a [generic type parameter](https://www.typescriptlang.org/docs/handbook/generics.html) would be even more ideal, because it means properties like `currentProvider` could be strongly typed, even if they are custom/non-standard.

Right now the only workaround is to cast the provider to `any`, which is not ideal.

#### Steps to reproduce the behavior

1. Set up TS project
2. Attempt to construct `Web3` instance with non-standard provider

### PR DESCRIPTION
**Pull request by odanado**
## Description
Fixes #3380 

The only method that `provider` should implement is the `send` function.
I'd like you to consider whether the interface of `EventEmitter` should be implemented or not.

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran ```npm run dtslint``` with success and extended the tests and types if necessary.
- [ ] I ran ```npm run test:unit``` with success.
- [ ] I have executed ``npm run test:cov`` and my test cases do cover all lines and branches of the added code.
- [ ] I ran ```npm run build-all``` and tested the resulting file/'s from  ```dist``` folder in a browser.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the live network.

### CODE REVIEW

File: packages/web3-core/types/index.d.ts [hunk 1]
```diff
@@ -410,9 +413,14 @@ export interface LogsOptions {
 
 export type BlockNumber = string | number | BN | BigNumber | 'latest' | 'pending' | 'earliest' | 'genesis';
 
+export interface AbstractProvider extends EventEmitter {
```
Comment (odanado) [inline packages/web3-core/types/index.d.ts]: I would like to consider the following points
- Using the `extends EventEmitter`.
- Remove `extends EventEmitter` (Leaving only the `send` function in the interface).
- Remove `extends EventEmitter` and directly define the `on`, `once`, and `removeListener` functions as well as the `WebsocketProviderBase`.

Comment (smithki) [reply packages/web3-core/types/index.d.ts]: My `$0.02` is to separate the core functionality from the subscription functionality. Not all custom providers support subscription features by default. Classes can implement multiple interfaces in TypeScript, so it shouldn't be problematic to export two interfaces.

I am not an active contributor to this code-base. This is my opinion only.

File: packages/web3-core/types/index.d.ts [hunk 2]
```diff
@@ -410,9 +413,14 @@ export interface LogsOptions {
...
+    send(payload: JsonRpcPayload, callback: (error: Error | null, result?: JsonRpcResponse) => void): void;
```
Comment (odanado) [inline packages/web3-core/types/index.d.ts:415]: The interface may also need to require sendAsync function for a library that only supports a legacy provider.

e.g. https://github.com/MetaMask/eth-json-rpc-middleware/blob/9464aa2085c63b43f1e5ed569bd08b0697c53d39/providerAsMiddleware.js#L6

File: packages/web3-core/types/index.d.ts (hunk 1 above)
Comment (ryanio) [reply packages/web3-core/types/index.d.ts]: Hey @odanado thanks for this PR :) It LGTM. For your 3 points, perhaps just on/once/removeListener is sufficient as the "bare minimum".

What are the types of `WebsocketProviderBase`?

Also, in light of [recent updates to EIP-1193](https://github.com/ethereum/EIPs/issues/2319#issuecomment-610610675), there is a new `request` method that would be great to add. I don't think having `sendAsync` would hurt either even though it's deprecated it has more long term support.

Comment (odanado) [reply packages/web3-core/types/index.d.ts]: @ryanio  Thank you for the comment.
I didn't know the `request` method of EIP-1193.

I thought that the interface of the `AbstractProvider` should be an only of `send` and `sendAsync`.
The reasons are as follows.
- The status of EIP-1193 is a draft.
- EIP-1193 is not yet fully implemented in Metamask

I think it should define a provider that has methods such as on/once/removeListener/request separately from `AbstractProvider`.

File: packages/web3-core/types/index.d.ts (hunk 2 above)
Comment (ryanio) [reply packages/web3-core/types/index.d.ts:415]: Hey @odanado thanks again for this PR and sorry for the delay, finally getting back to it :)

I think adding `sendAsync` would be a great idea, do you mind adding it? [ethers.js/web3-provider](https://github.com/ethers-io/ethers.js/blob/56af4413b1dd1787db68985e0b612b63d86fdf7c/packages/providers/src.ts/web3-provider.ts#L17) defines it like so:

```typescript
sendAsync?: (request: { method: string, params?: Array<any> }, callback: (error: any, response: any) => void) => void
```

I'll add the latest EIP-1193 compatibility in a subsequent PR since we just moved the document into Last Call with a 6-week review period and MetaMask should be deploying their implementation soon.

**Review by ryanio — CHANGES_REQUESTED** [review]

File: packages/web3-core/types/index.d.ts (hunk 2 above)
Comment (odanado) [reply packages/web3-core/types/index.d.ts:415]: @ryanio Thank you for the comment.
I updated.

- remove EventEmitter
- add sendAsync method

**Comment by ryanio** [comment]
Thanks for adding sendAsync  🙌 looks like there is [a small dtslint issue](https://github.com/ethereum/web3.js/pull/3451/checks?check_run_id=642041392#step:5:151).

**Comment by odanado** [comment]
@ryanio I forgot that fix a test.
I updated the test.

**Review by ryanio — APPROVED** [review]
Looks great, thanks!
