### PR TITLE
Nikos/5711/transaction with local wallet index should support to as a wallet index

### LINKED ISSUE #5711: `TransactionWithLocalWalletIndex` should support `to` as a wallet index
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```typescript
export interface TransactionWithLocalWalletIndex extends TransactionBase {
    from?: Numbers;
}
```

### Expected Behavior

```typescript
export interface TransactionWithLocalWalletIndex extends TransactionBase {
    from?: Numbers;
    to?: Numbers;
}
```

### Steps to Reproduce

Try to send a transaction where `to` is the index of an account in the local wallet

### Web3.js Version

4.0.1-alpha-2

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version: 

### Anything Else?

_No response_

### PR DESCRIPTION
**Pull request by nikoulai**
## Description

closes #5711

## Checklist for 4.x:

- [ ] I have selected the correct 4.x base branch.
- [ ] Within the description, the feature or issue is discussed in detail or an issue is linked.   
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added any required tests for the changes I made 
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `yarn` successfully
- [ ] I ran `yarn lint` successfully
- [ ] I ran `yarn build:web` successfully
- [ ] I ran `yarn test:unit` successfully
- [ ] I ran `yarn test:integration` successfully
- [ ] I ran `compile:contracts` successfully
- [ ] I have tested my code.
- [ ] I have updated the corresponding `CHANGELOG.md` file in the packages I have edited.

### CODE REVIEW

File: packages/web3-errors/src/error_codes.ts [hunk 1]
```diff
@@ -52,38 +52,39 @@ export const ERR_TX_OUT_OF_GAS = 406;
...
+
+export const ERR_TX_NOT_FOUND = 431;
+export const ERR_TX_SEND_TIMEOUT = 432;
+export const ERR_TX_BLOCK_TIMEOUT = 433;
+
+export const ERR_TX_SIGNING = 434;
+export const ERR_TX_GAS_MISMATCH = 435;
+
+export const ERR_TX_CHAIN_MISMATCH = 436;
+export const ERR_TX_HARDFORK_MISMATCH = 437;
```
Comment (jdevcs) [inline packages/web3-errors/src/error_codes.ts]: This will be breaking change for many error codes, and we can avoid it by making` ERR_TX_INVALID_RECEIVER = 437` ?

Comment (nikoulai) [reply packages/web3-errors/src/error_codes.ts]: resolved. thanks

File: CHANGELOG.md [hunk 2]
```diff
@@ -945,3 +945,9 @@ should use 4.0.1-alpha.0 for testing.
 -   These types were moved from `web3-eth-accounts` to `web3-types` package: Cipher, CipherOptions, ScryptParams, PBKDF2SHA256Params, KeyStore (#5581 )
 
 ## [Unreleased]
+
+### Fixed
+
+#### web3-eth
+
+-   Enable transaction with local wallet index in the `to` field (#5731)
```
Comment (jdevcs) [inline CHANGELOG.md:953]: Thanks @nikoulai , also add changelog in root under web3-error and web3-error package's own changelog

Comment (nikoulai) [reply CHANGELOG.md:953]: added, thanks for the comment

**Review by avkos — APPROVED** [review]

File: packages/web3-eth/src/utils/transaction_builder.ts [hunk 3]
```diff
@@ -53,19 +55,22 @@ import { getTransactionGasPricing } from './get_transaction_gas_pricing';
 import { transactionSchema } from '../schemas';
 import { InternalTransaction } from '../types';
 
-export const getTransactionFromAttr = (
+const isFromAttr = (attr: 'from' | 'to'): attr is 'from' => attr === 'from';
```
Comment (Spacesai1or) [inline packages/web3-eth/src/utils/transaction_builder.ts]: I don't think this function is necessary since it's only used in two places, I think using the check `attr === 'from'` should suffice

File: packages/web3-eth/src/utils/transaction_builder.ts [hunk 4]
```diff
@@ -76,15 +81,24 @@ export const getTransactionFromAttr = (
...
+		if (!isNullish(web3Context.defaultAccount)) return web3Context.defaultAccount;
+	}
 
 	return undefined;
 };
 
+export const getTransactionFromAttr = getTransactionFromOrToAttr.bind(undefined, 'from');
+
+export const getTransactionToAttr = getTransactionFromOrToAttr.bind(undefined, 'to');
+
```
Comment (Spacesai1or) [inline packages/web3-eth/src/utils/transaction_builder.ts]: I think these methods should be removed and `getTransactionFromOrToAttr` should be exported and used instead

File: packages/web3-eth/test/integration/web3_eth/send_transaction.test.ts [hunk 5]
```diff
@@ -83,6 +83,69 @@ describe('Web3Eth.sendTransaction', () => {
...
+		const response = await web3EthWithWallet.sendTransaction(transaction);
+		expect(response.status).toBe(BigInt(1));
+
+		const minedTransactionData = await web3EthWithWallet.getTransaction(
+			response.transactionHash,
+		);
+
+		expect(minedTransactionData).toMatchObject({
+			from: tempAcc.address,
+			to: wallet.get(0)?.address.toLocaleLowerCase(),
```
Comment (Spacesai1or) [inline packages/web3-eth/test/integration/web3_eth/send_transaction.test.ts]:
```suggestion
			to: wallet.get(0)?.address.toLowerCase(),
```

File: packages/web3-eth/test/integration/web3_eth/send_transaction.test.ts [hunk 6]
```diff
@@ -83,6 +83,69 @@ describe('Web3Eth.sendTransaction', () => {
...
+		const response = await web3EthWithWallet.sendTransaction(transaction);
+		expect(response.status).toBe(BigInt(1));
+
+		const minedTransactionData = await web3EthWithWallet.getTransaction(
+			response.transactionHash,
+		);
+
+		expect(minedTransactionData).toMatchObject({
+			from: tempAcc.address,
+			to: wallet.get(1)?.address.toLocaleLowerCase(),
```
Comment (Spacesai1or) [inline packages/web3-eth/test/integration/web3_eth/send_transaction.test.ts]:
```suggestion
			to: wallet.get(1)?.address.toLowerCase(),
```

File: packages/web3-types/src/eth_types.ts [hunk 7]
```diff
@@ -367,8 +367,10 @@ export interface TransactionCall extends Transaction {
 	to: Address;
 }
 
-export interface TransactionWithLocalWalletIndex extends TransactionBase {
+export interface TransactionWithLocalWalletIndex extends Omit<TransactionBase, 'to'> {
 	from?: Numbers;
+	// eslint-disable-next-line @typescript-eslint/ban-types
+	to?: Address | Numbers | null;
```
Comment (Spacesai1or) [inline packages/web3-types/src/eth_types.ts]: `to` being `Address | null` is already handled by the type [TransactionBase](https://github.com/web3/web3.js/blob/c4e255d277a6b57a92e0325eefa79852ba7dd864/packages/web3-types/src/eth_types.ts#L337), so it should just be listed as `Numbers` here. The problem is `from` could be the local wallet index while `to` is `Address | null`, so I see why you did this, but it doesn't work for the inverse where `to` is an index but `from` is `Address | null`

I'm not sure how else to this besides introducing the following types: `TransactionWithFromLocalWalletIndex`, `TransactionWithToLocalWalletIndex`, and `TransactionWithFromAndToLocalWalletIndex`, so definitely open to suggestions. I've opened #5748 to implement this (doesn't update the `CHANGELOG`s, so that will need to be done if you decided to merge it)

**Review by Spacesai1or — CHANGES_REQUESTED** [review]

**Review by jdevcs — APPROVED** [review]

**Review by Spacesai1or — APPROVED** [review]
