### PR TITLE
Fix odd length hex string conversion

### LINKED ISSUE #5073: `bytesToBuffer` does not work for 0 and 1 integer values
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```typescript
bytesToBuffer(numberToHex(1))
```

returns empty buffer `<Buffer >`

### Expected Behavior

```typescript
bytesToBuffer(numberToHex(1))
```

should return `<Buffer 01>`

### Steps to Reproduce

```typescript
bytesToBuffer(numberToHex(1))
```

### Web3.js Version

4.x

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version: 

### Anything Else?

The following code is responsible for the issue. 

https://github.com/ChainSafe/web3.js/blob/82574a2587810f9bea26ba65da48fe667162e573/packages/web3-utils/src/converters.ts#L88-L90

### PR DESCRIPTION
**Pull request by nikoulai**
## Description

#5073 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

File: packages/web3-utils/src/converters.ts [hunk 1]
```diff
@@ -86,7 +86,8 @@ export const bytesToBuffer = (data: Bytes): Buffer | never => {
 	}
 
 	if (typeof data === 'string' && isHexStrict(data)) {
-		return Buffer.from(data.slice(2), 'hex');
+		const finalData = data.length % 2 === 0 ? data : `0${data}`;
```
Comment (nazarhussain) [inline packages/web3-utils/src/converters.ts]: This code block executes when `data` is already prefixed with `0x`, so returning `0${data}` will end up wrong hex string. e.g. If `data='0x1` it will return `00x1`.

Also add a few tests for this specific case.

**Review by nazarhussain — CHANGES_REQUESTED** [review]

**Review by avkos — APPROVED** [review]

File: packages/web3-utils/src/converters.ts (hunk 1 above)
Comment (avkos) [inline packages/web3-utils/src/converters.ts]:
```suggestion
		const finalData = data.replace(/^(?!0x)/,'0x') ;
```

**Review by avkos — CHANGES_REQUESTED** [review]

File: packages/web3-utils/src/converters.ts (hunk 1 above)
Comment (avkos) [reply packages/web3-utils/src/converters.ts]: It’s just stating if any starting does not start with 0x, just replace the start with 0x.
Also, add a few test cases for this. It’s very tricky but essential code.

Comment (nikoulai) [reply packages/web3-utils/src/converters.ts:89]: I had in mind the input from `numberToHex`, very good point thanks!!
I didn't find any tests for `bytesToBuffer`, I'll add them including this case

Comment (nikoulai) [reply packages/web3-utils/src/converters.ts]: I could use this function in preprocessing of `data` variable to ensure it starts with `0x`, but, what I want to do is to ensure that the length of the string is even, in order to `Buffer.from` work as wanted.

File: packages/web3-utils/src/converters.ts [hunk 2]
```diff
@@ -86,7 +86,8 @@ export const bytesToBuffer = (data: Bytes): Buffer | never => {
 	}
 
 	if (typeof data === 'string' && isHexStrict(data)) {
-		return Buffer.from(data.slice(2), 'hex');
+		const finalData = `${/^(..)*$/.test(data) ? '' : '0'}${data.replace(/0(x|X)/, '')}`;
```
Comment (nazarhussain) [inline packages/web3-utils/src/converters.ts]: Mixing up the string interpolation with the regular expressions does make it difficult to read. What do you think about this approach? 

```suggestion
        const eventLength = data.length + (data.length % 2);
		const finalData = data.toLowerCase().replace('0x', '').padStart(eventLength, '0')
```

File: packages/web3-utils/test/fixtures/converters.ts [hunk 3]
```diff
@@ -267,3 +267,15 @@ export const toCheckSumValidData: [string, string][] = [
...
 ];
+
+export const bytesToBufferInvalidData: [any, string][] = bytesToHexInvalidData;
+
+export const bytesToBufferValidData: [Bytes, Buffer][] = [
+	[new Uint8Array([72]), Buffer.from('48', 'hex')],
+	[new Uint8Array([72, 12]), Buffer.from('480c', 'hex')],
+	['0x9c12', Buffer.from('9c12', 'hex')],
+	['0X12c6', Buffer.from('12c6', 'hex')],
+	['0X1', Buffer.from('01', 'hex')],
```
Comment (nazarhussain) [inline packages/web3-utils/test/fixtures/converters.ts:280]:
```suggestion
	['0X1', Buffer.from('01', 'hex')],
	['0x1', Buffer.from('01', 'hex')],
	['0x0', Buffer.from('00', 'hex')],	
    ['0X0', Buffer.from('00', 'hex')],	
    ['1234', Buffer.from('1233', 'hex')],	
```

Comment (nazarhussain) [reply packages/web3-utils/test/fixtures/converters.ts:280]: Also add these invalid use cases as well. 

```
    ['1', Buffer.from('01', 'hex')],	    
    ['0', Buffer.from('00', 'hex')],	    

```

**Review by nazarhussain — CHANGES_REQUESTED** [review]

**Review by avkos — APPROVED** [review]
Approve, except for comments from Nazar

File: packages/web3-utils/src/converters.ts (hunk 2 above)
Comment (nikoulai) [reply packages/web3-utils/src/converters.ts]: Of course, I'm ok with change! I made it, I just made a modification, because `eventLength` included the `0x` prefix and finally would pad a string with '000`  or  `00`,

File: packages/web3-utils/test/fixtures/converters.ts (hunk 3 above)
Comment (nikoulai) [reply packages/web3-utils/test/fixtures/converters.ts:280]: Add some of them, but, made some changes

As valid I added:
['0x1234', Buffer.from('1233', 'hex')] instead of ['1234', Buffer.from('1233', 'hex')]

and in invalids:
['1', Buffer.from('01', 'hex')],	    
['0', Buffer.from('00', 'hex')] 
I changes the `Buffer.from` to the error message.
Are these changes ok?

**Review by luu-alex — APPROVED** [review]

**Review by jdevcs — APPROVED** [review]

File: packages/web3-utils/test/fixtures/converters.ts (hunk 3 above)
Comment (nazarhussain) [reply packages/web3-utils/test/fixtures/converters.ts:280]: Sure

File: packages/web3-utils/src/converters.ts (hunk 2 above)
Comment (nazarhussain) [reply packages/web3-utils/src/converters.ts]: Sure, please make the change accordingly.

**Review by nazarhussain — APPROVED** [review]
