### PR TITLE
`defaultTransactionBuilder` Refactors and Add Gas Pricing to `sendTransaction`

### LINKED ISSUE #4509: Don't autofill gasPrice on transactions
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have a report from etherscan that they are using web3.js, and it seems to be auto-filling a `gasPrice` parameter, which MetaMask currently interprets to mean the site is deliberately overriding the wallet's own suggested price. This is resulting in user transaction overpayment.

### Expected Behavior

Unless a developer has explicitly included a `gasPrice` parameter, no `gasPrice` parameter should be passed to the provider in a `sendTransaction` call.

### Steps to Reproduce

```javascript
var Web3 = require('web3');
var web3 = new Web3(Web3.givenProvider || 'ws://some.local-or-remote.node:8546');

// using the promise
web3.eth.sendTransaction({
    from: '0xde0B295669a9FD93d5F28D9Ec85E40f4cb697BAe',
    to: '0x11f4d0A3c12e86B4b5F39B213F7E19D048276DAe',
    value: '1000000000000000'
})
.then(function(receipt){

});
```

### Web3.js Version

1.5.3

### Environment

- Operating System: All
- Browser: All
- Node.js Version: 
- NPM Version: 

### Anything Else?

_No response_

### PR DESCRIPTION
**Pull request by Spacesai1or**
- `Web3ConfigOptions`'s `defaultBlock` type changed from `HexString` to `BlockNumberOrTag`
- Split `defaultTransactionBuilder` into several functions, some which are exported to be used elsewhere in the code
    - `getTransactionFrom`
    - `getTransactionNonce`
    - `getTransactionType`
    - `getTransactionGasPricing`
        - This was pulled into it's own file: `packages/web3-eth/src/utils/get_transaction_gas_pricing.ts` due to it's size
- Update `sendTransaction` (in `packages/web3-eth/src/rpc_method_wrappers.ts`) to fetch gas pricing (`gasPrice` or `maxPriorityFeePerGas` and `maxFeePerGas`) if not provided by user
- Add `options` object to `sendTransaction`, currently has one setting: `ignoreGasPricing`
    - `ignoreGasPricing = true` will not auto fill gas pricing as it always done (if not provided by user) in 1.x. Addresses issue #4509

---

closes #4509

### CODE REVIEW

File: packages/web3-eth/src/utils/transaction_builder.ts [hunk 1]
```diff
@@ -1,40 +1,73 @@
...
+export const getTransactionFrom = (
+	web3Context: Web3Context<EthExecutionAPI>,
+	privateKey?: HexString | Buffer,
+) => {
+	if (privateKey !== undefined) return privateKeyToAddress(privateKey);
+	if (web3Context.defaultAccount !== null) return web3Context.defaultAccount;
+	// TODO if (web3.eth.accounts.wallet) Try to fill using local wallet
+
+	return undefined;
+};
```
Comment (nazarhussain) [inline packages/web3-eth/src/utils/transaction_builder.ts]: Do we need to get transaction or account or address?

**Review by nazarhussain — CHANGES_REQUESTED** [review]

File: packages/web3-eth/src/utils/transaction_builder.ts [hunk 2]
```diff
@@ -1,40 +1,73 @@
...
+import { Address, convertToValidType, HexString, ValidTypes } from 'web3-utils';
+import { TransactionDataAndInputError, UnableToPopulateNonceError } from '../errors';
+// eslint-disable-next-line import/no-cycle
+import { getTransactionCount } from '../rpc_method_wrappers';
 import { chain, hardfork, Transaction } from '../types';
 import { detectTransactionType } from './detect_transaction_type';
+// eslint-disable-next-line import/no-cycle
+import { getTransactionGasPricing } from './get_transaction_gas_pricing';
+
+export const getTransactionFrom = (
```
Comment (nazarhussain) [inline packages/web3-eth/src/utils/transaction_builder.ts]:
```suggestion
export const getTransactionFromAttr = (
```

**Review by nazarhussain — CHANGES_REQUESTED** [review]

**Review by nazarhussain — APPROVED** [review]
Apart from that one comment, rest LGTM.

**Review by luu-alex — APPROVED** [review]
