### PR TITLE
Return Subscription object without await

### LINKED ISSUE #5203: Subscription object should be returned without await
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently the user have to use `await` to fetch the subscription object before listening to it. 

```ts
(await myContract.events.MyEvent()).on('data', console.log)
```

### Expected Behavior

Logically this can be avoid that will make it consistent with the `1.x`. We can throw `error` event if it fails to subscribe. 

```ts
myContract.events.MyEvent().on('data', console.log).on('error', console.error); 
```

or

```ts
myContract.events.MyEvent().on('data', console.log).catch(console.error); 
```

### Steps to Reproduce

Mentioned in example above. 

### Web3.js Version

4.x

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version: 

### Anything Else?

To make this work, we have to refactor the subscription manager. It's trivial change but not complex.

### PR DESCRIPTION
**Pull request by nikoulai**
## Description

Fixes #5203

### CODE REVIEW

**Review by luu-alex — APPROVED** [review]

File: packages/web3-eth-contract/src/contract.ts [hunk 1]
```diff
@@ -1050,7 +1051,9 @@ export class Contract<Abi extends ContractAbi>
 				{ requestManager: this.requestManager },
 			);
 
-			await this.subscriptionManager?.addSubscription(sub);
+			this.subscriptionManager?.addSubscription(sub).catch(() => {
+				throw new SubscriptionError('Failed to subscribe.');
+			});
```
Comment (nazarhussain) [inline packages/web3-eth-contract/src/contract.ts]: I would suggest to create an `error` event and `emit` the error on `sub` object in this particular case.

**Review by nazarhussain — CHANGES_REQUESTED** [review]

**Review by jdevcs — APPROVED** [review]
apart from Nazar comments LGTM

**Review by avkos — APPROVED** [review]

**Review by nazarhussain — APPROVED** [review]
