### PR TITLE
Handling of the "null" response from provider

### LINKED ISSUE #5319: Handling of the "null" response from provider
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In some cases the provider returns `null`, which can't be handled by the `request manager` and cause runtime error. 

### Expected Behavior

There should not be an error and the `null` response should be returned from the request manager. 

### Steps to Reproduce

Send a transaction receipt request for a hash which does not exists. 

### Web3.js Version

4.x

### Environment

N/A

### Anything Else?

_No response_

### PR DESCRIPTION
**Pull request by nazarhussain**
## Description

Fixes #5319

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [x] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [x] I ran `npm run build` with success.
- [x] I have tested the built `dist/web3.min.js` in a browser.
- [x] I have tested my code on the live network.
- [x] I have checked the Deploy Preview and it looks correct.
- [x] I have updated the `CHANGELOG.md` file in the root folder.

### CODE REVIEW

**Review by avkos — APPROVED** [review]

File: packages/web3-core/src/web3_request_manager.ts [hunk 1]
```diff
@@ -274,6 +274,16 @@ export class Web3RequestManager<
 		response: JsonRpcResponse<ResultType, ErrorType>,
 		{ legacy, error }: { legacy: boolean; error: boolean },
 	): JsonRpcResponse<ResultType> | never {
+		if (isNullish(response)) {
```
Comment (jdevcs) [inline packages/web3-core/src/web3_request_manager.ts:277]: is any provider returning null for valid requests (for which some valid result is expected)?

Comment (jdevcs) [inline packages/web3-core/src/web3_request_manager.ts:277]: can you share rpc request and eth node you used for this case?

**Review by jdevcs — APPROVED** [review]

File: packages/web3-core/src/web3_request_manager.ts (hunk 1 above)
Comment (nazarhussain) [reply packages/web3-core/src/web3_request_manager.ts:277]: It was tested for `eth_getTransactionReceipt` with ganache for a transaction hash which is not part of the block yet. 

https://github.com/ethereum/execution-apis/blob/main/src/eth/transaction.yaml#L42
