### PR TITLE
6801 Fill gas price when baseFeePerGas==='0x0'

### LINKED ISSUE #6801: `fillGasPrice` fundamentally changed transactions, should have been a breaking change?
#### Expected behavior

Up until v4.0.3, Contract transactions would go through without explicitly estimating gas prices on the caller side; web3js did it automatically. We could do this and everything would work fine:
```js
  const contract = provider && new provider.eth.Contract(abi, address);
```

#### Actual behavior

Since v4.1.0, this behavior changed as the default value for `fillGasPrice` is set as `false`. It becomes mandatory to do this:
```js
  const contract = provider && new provider.eth.Contract(abi, address, {
    gasPrice: await provider.eth.getGasPrice(), // <--- this line becomes mandatory
  });
```

Also, the `prepareTransactionForSigning` is never called with this parameter (or with `fillGasLimit` BTW), meaning the default Contract object instances cannot be given those flags without a custom `transactionBuilder` method in the `web3Context` of the caller, which is overkill just to set simple boolean flags.

In practice, unless I am missing something obvious (I could be, but definitely need someone to point it out and I would greatly appreciate it!), it seems we are stuck to manually estimating gas for each contract/transaction beforehand.

E.g. every single transaction, processed via metamask on either BNB Mainnet or Testnet, for which we do not estimate gas price explicitly, fails, as it defaults to 2,5 GWEI which is below the minimum necessary on both networks for txs to go through.

This was buried in the changelog in the line:
> sendTransaction will have gas filled by default using method estimateGas unless transaction builder options.fillGas is false

Please note that
- there is no `fillGas` option anywhere;
- `fillGasPrice` and `fillGasLimit` are not easily set without a custom `transactionBuilder` in the Contract's web3Context;
- and this actually seems to be a lie because the default value for the option is `false` and not `true`.

As mentioned, if I am wrong I definitely need clarification here as documentation and examples are scarce around this.

### PR DESCRIPTION
**Pull request by avkos**
## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](https://github.com/web3/web3.js/blob/4.x/.github/CONTRIBUTING.md).

Fixes #6801 

BSC chain returns `baseFeePerGas==='0x0'` but supports type 2 transactions.
Fix is set current `gasPrice` to `maxPriorityFeePerGas` and `maxFeePerGas`

```ts

const contract = new web3.eth.Contract(ERC20TokenAbi, '0x63C872fC0Add8129F3d18f7975aCbD335356e2aE')
const res = await contract.methods
        .transfer('0x8f3e9c1Bd65EB267d19B176A73217524DC21A5ca', 1)
        .send({
            from: acc.address,
        });
console.log(res);
```

```
{
  blockHash: '0x8cd5b444a0d556fea0c94c27dd596dd445a41768dde4a9efee0ed37d01f0ad5b',
  blockNumber: 40514564n,
  cumulativeGasUsed: 364295n,
  effectiveGasPrice: 5050000000n,
  from: '0xe4beef667408b99053dc147ed19592ada0d77f59',
  gasUsed: 52321n,
  logs: [
    {
      address: '0x63c872fc0add8129f3d18f7975acbd335356e2ae',
      topics: [Array],
      data: '0x0000000000000000000000000000000000000000000000000000000000000001',
      blockNumber: 40514564n,
      transactionHash: '0x0cc26c683e87e4c1792fb00de8fd8748e171d0c3e279b63731664dcdefaa6b60',
      transactionIndex: 2n,
      blockHash: '0x8cd5b444a0d556fea0c94c27dd596dd445a41768dde4a9efee0ed37d01f0ad5b',
      logIndex: 1n,
      removed: false
    }
  ],
  logsBloom: '0x00000000000000000000000000000000000000000000040000000000000000000000000000000010000000000000000000200000000004000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000100000000020000000000000',
  status: 1n,
  to: '0x63c872fc0add8129f3d18f7975acbd335356e2ae',
  transactionHash: '0x0cc26c683e87e4c1792fb00de8fd8748e171d0c3e279b63731664dcdefaa6b60',
  transactionIndex: 2n,
  type: 2n,
  events: {
    Transfer: {
      address: '0x63c872fc0add8129f3d18f7975acbd335356e2ae',
      topics: [Array],
      data: '0x0000000000000000000000000000000000000000000000000000000000000001',
      blockNumber: 40514564n,
      transactionHash: '0x0cc26c683e87e4c1792fb00de8fd8748e171d0c3e279b63731664dcdefaa6b60',
      transactionIndex: 2n,
      blockHash: '0x8cd5b444a0d556fea0c94c27dd596dd445a41768dde4a9efee0ed37d01f0ad5b',
      logIndex: 1n,
      removed: false,
      returnValues: [Object],
      event: 'Transfer',
      signature: '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
      raw: [Object]
    }
  }
}

```

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run lint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

### CODE REVIEW

File: packages/web3-eth/src/utils/get_transaction_gas_pricing.ts [hunk 1]
```diff
@@ -38,14 +38,17 @@ async function getEip1559GasPricing<ReturnFormat extends DataFormat>(
...
-	if (!isNullish(transaction.gasPrice)) {
+	let gasPrice: Numbers | undefined;
+	if (isNullish(transaction.gasPrice) && BigInt(block.baseFeePerGas) === BigInt(0)) {
+		gasPrice = await getGasPrice(web3Context, returnFormat);
+	}
+	if (!isNullish(transaction.gasPrice) || !isNullish(gasPrice)) {
 		const convertedTransactionGasPrice = format(
 			{ format: 'uint' },
-			transaction.gasPrice as Numbers,
+			transaction.gasPrice ?? gasPrice,
```
Comment (jdevcs) [inline packages/web3-eth/src/utils/get_transaction_gas_pricing.ts:51]: these should be covered with tests

**Review by jdevcs — APPROVED** [review]
changelog update, thanks

**Review by luu-alex — APPROVED** [review]
