### PR TITLE
fix: web3-validator ajv memory leak

### LINKED ISSUE #5515: Memory leak for the `fromWei` utility function for stirng input
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If the input value for the `fromWei` function is a string type, it leaks the memory and heap continuously increased. 

### Expected Behavior

There should not be a memory leak regardless of the type of input. 

### Steps to Reproduce

```js
// test.js
const { fromWei } = require('web3-utils');

const limit = 2_000_000;

const toKb = num => (num / 1024).toFixed();

new Array(limit).fill('10000').forEach((d, i) => {
	if (i % 10000 === 0) {
		const mem = process.memoryUsage();
		console.log(`heap: ${toKb(mem.heapUsed)}, total: ${toKb(mem.heapTotal)} rss: ${toKb(mem.rss)}`);
	}
	fromWei(d, 'ether');
});
```

Start the node process with following options. 

```bash
NODE_OPTIONS=--max-old-space-size=500 node test.js
```

### Web3.js Version

4.x

### Environment

- Operating System: Mac/Linux
- Node.js Version: 16.6
- NPM Version: 8.11

### Anything Else?

This behaviour was not seen with the 1.x.

### PR DESCRIPTION
**Pull request by mpetrunic**
## Description

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../blob/1.x/CONTRIBUTIONS.md).

Ajv from version 7 onwards uses object references to compile and cache schema. Since web3.js is passing a new object/array for every single validation, this causes every object to be compiled and attached to the schema cache which results in a massive memory leak.

This PR removes that leak by stringifying schemas and using the stringified form as the cache key. But since we now store both string, and compiled schema, memory usage is higher. 

Also, we still have leak if the user starts using one-time validation schemas. Which we would need to remove or they end up permanently attached to the default validator.

resolves #5515

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist for 1.x:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run dtslint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:cov` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` with success.
- [ ] I have tested the built `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.

## Checklist for 4.x:

- [x] I have selected the correct 4.x base branch.
- [x] Within the description, the feature or issue is discussed in detail or an issue is linked.   
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added any required tests for the changes I made 
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I ran `yarn` successfully
- [x] I ran `yarn lint` successfully
- [ ] I ran `yarn build:web` successfully
- [x] I ran `yarn test:unit` successfully
- [ ] I ran `yarn test:integration` successfully
- [ ] I ran `compile:contracts` successfully
- [ ] I have tested my code.
- [ ] I have updated the corresponding `CHANGELOG.md` file in the packages I have edited.

### CODE REVIEW

**Review by jdevcs — APPROVED** [review]

**Review by luu-alex — APPROVED** [review]

File: packages/web3-validator/src/web3_validator.ts [hunk 1]
```diff
@@ -98,7 +98,11 @@ export class Web3Validator {
 			]);
 		}
 
-		if (!this._validator.validate(jsonSchema, data)) {
+		const schemaKey = JSON.stringify(jsonSchema);
```
Comment (Muhammad-Altabba) [inline packages/web3-validator/src/web3_validator.ts]: What do you think about using the hash of the `jsonSchema` as the key? 
We can use a simple hashing function that we need to add like this for example:
```javascript
String.prototype.hashCode = function() {
  var hash = 0,
    i, chr;
  if (this.length === 0) return hash;
  for (i = 0; i < this.length; i++) {
    chr = this.charCodeAt(i);
    hash = ((hash << 5) - hash) + chr;
    hash |= 0; // Convert to 32bit integer
  }
  return hash;
}

```

And then the code will be:
```suggestion
		const schemaKey = JSON.stringify(jsonSchema).hashCode()
```

@jdevcs & @luu-alex your recommendation is required. Do you think we should use a simple hashing function as above (that is great for the task)? Or should we utilize `keccak256` from `ethereum-cryptography/keccak` (we would need to add it to the dependencies of web3-validator)? Or should we not using any hash for this?

Thanks all,

**Review by Muhammad-Altabba — CHANGES_REQUESTED** [review]
Thanks for your contribution.
It seems great!
However, I think it would be better to use a hash for the key instead of the full JSON. And I added a comment regarding this.
Thanks,

File: packages/web3-validator/src/web3_validator.ts (hunk 1 above)
Comment (jdevcs) [reply packages/web3-validator/src/web3_validator.ts]: Good suggestion, Thanks @Muhammad-Altabba . We can definitely use hash as key for adding or querying schema in ajv. Currently there is already dependency of eth-cryptography in validator package https://github.com/web3/web3.js/blob/fe037a09e9da7882c5a2e1707a23e778c3558a74/packages/web3-validator/package.json#L31 so I'll suggest to use some existing hash algo ( for avoiding collisions ) instead of simple one.

**Comment by mpetrunic** [comment]
I don't think I caused tests to fail, they seem to be flaky but I cannot rerun them^^

**Comment by Muhammad-Altabba** [comment]
> I don't think I caused tests to fail, they seem to be flaky but I cannot rerun them^^

Sorry @mpetrunic but it seems to be caused by the last update as the pipeline issues keep showing when I re-run it 3 times. And it is only shown after the latest update to use the hash function. And so it would be so nice of you to count for the time of the hash function and to count how many times this hash function is called (to check if there is something wrong with the code that causes unneeded calls for example). 
Thanks,

**Comment by mpetrunic** [comment]
> > I don't think I caused tests to fail, they seem to be flaky but I cannot rerun them^^
> 
> Sorry @mpetrunic but it seems to be caused by the last update as the pipeline issues keep showing when I re-run it 3 times. And it is only shown after the latest update to use the hash function. And so it would be so nice of you to count for the time of the hash function and to count how many times this hash function is called (to check if there is something wrong with the code that causes unneeded calls for example). Thanks,

Do you suggest increasing the timeout on those tests or reverting the last commit? 

I mean converting to bytes, hashing, and converting to hex has some cost and this is quite a hot path as it gets called for every validation.

**Comment by Muhammad-Altabba** [comment]
> > > I don't think I caused tests to fail, they seem to be flaky but I cannot rerun them^^
> > 
> > 
> > Sorry @mpetrunic but it seems to be caused by the last update as the pipeline issues keep showing when I re-run it 3 times. And it is only shown after the latest update to use the hash function. And so it would be so nice of you to count for the time of the hash function and to count how many times this hash function is called (to check if there is something wrong with the code that causes unneeded calls for example). Thanks,
> 
> Do you suggest increasing the timeout on those tests or reverting the last commit?
> 
> I mean converting to bytes, hashing, and converting to hex has some cost and this is quite a hot path as it gets called for every validation.

Many thanks @mpetrunic
And what do you think about using a cheaper hash function like the one called `hashCode` here:
https://github.com/web3/web3.js/pull/5574#discussion_r1010172367

**Comment by mpetrunic** [comment]
> > > > I don't think I caused tests to fail, they seem to be flaky but I cannot rerun them^^
> > > 
> > > 
> > > Sorry @mpetrunic but it seems to be caused by the last update as the pipeline issues keep showing when I re-run it 3 times. And it is only shown after the latest update to use the hash function. And so it would be so nice of you to count for the time of the hash function and to count how many times this hash function is called (to check if there is something wrong with the code that causes unneeded calls for example). Thanks,
> > 
> > 
> > Do you suggest increasing the timeout on those tests or reverting the last commit?
> > I mean converting to bytes, hashing, and converting to hex has some cost and this is quite a hot path as it gets called for every validation.
> 
> Many thanks @mpetrunic And what do you think about using a cheaper hash function like the one called `hashCode` here: [#5574 (comment)](https://github.com/web3/web3.js/pull/5574#discussion_r1010172367)

It generates a 32bit number as the hash. I don't think that has enough collision resistance. And collision here would be a nightmare to debug.

Ideally, we would use md5 or sha1 but they are not available so I switched now to blake2b which should be the fastest.

**Review by Muhammad-Altabba — APPROVED** [review]

**Comment by jdevcs** [comment]
Merged this in to 4.x even there is release branch out there as: https://github.com/web3/web3.js/pull/5580#issuecomment-1299012378
