### PR TITLE
Listening events on v4 is not working

### LINKED ISSUE #5989: Listening events on v4 is not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When contract events happen on the chain, web3 v4 does not do anything

### Expected Behavior

When contract events happen on-chain should trigger a callback.

### Steps to Reproduce

1. Open [stackblitz main.ts](https://stackblitz.com/edit/vitejs-vite-enrpyq?file=src/main.ts) there should be all run-able code
2. Start new [remix](https://remix.ethereum.org/) project with a basic template
3. Change all content from `1_Storage.sol` with one from [stackblitz Storage.sol](https://stackblitz.com/edit/vitejs-vite-enrpyq?file=Storage.sol)
4. Build a contract and deploy it with an `Injected Provider` - get a contract address
5. Update `contractAddress` inside [stackblitz main. ts](https://stackblitz.com/edit/vitejs-vite-enrpyq?file=src/main.ts) with the contract address from the remix
6. just in case save all inside stackblitz and refresh page 
7. call `store` method with some numeric value from remix
8. watch changes on stackblitz preview

eventually you will get something like this
image

### Web3.js Version

4.0.1-rc.0

### Environment

_No response_

### Anything Else?

Events are set as https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#contract-events there is nothing breaking in the migration guide https://docs.web3js.org/docs/guides/web3_migration_guide/contracts_migration_guide
and in tests, seems you can listen for events without providing any options
https://github.com/web3/web3.js/blob/8463f6bd45d79874b004ea128bb9d8aec63431b8/packages/web3-eth-contract/test/integration/contract_events.test.ts#L59

### PR DESCRIPTION
**Pull request by avkos**
## Description

Fixes #5989 

metamask mov

Please include a summary of the changes and be sure to follow our [Contribution Guidelines](../CONTRIBUTIONS.md).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran `npm run lint` with success and extended the tests and types if necessary.
- [ ] I ran `npm run test:unit` with success.
- [ ] I ran `npm run test:coverage` and my test cases cover all the lines and branches of the added code.
- [ ] I ran `npm run build` and tested `dist/web3.min.js` in a browser.
- [ ] I have tested my code on the live network.
- [ ] I have checked the Deploy Preview and it looks correct.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have linked Issue(s) with this PR in "Linked Issues" menu.

### CODE REVIEW

**Review by Muhammad-Altabba — COMMENTED** [review]
Could we please have tests for the added logic?

**Comment by avkos** [comment]
> Could we please have tests for the added logic?

Yes. I am working on it. but unfortunately, it will be not browser+metamask test, just unit test

File: packages/web3-core/src/web3_subscriptions.ts [hunk 1]
```diff
@@ -74,7 +74,20 @@ export abstract class Web3Subscription<
 			err: Error | undefined,
 			data?: JsonRpcSubscriptionResult | JsonRpcNotification<Log>,
```
Comment (Spacesai1or) [inline packages/web3-core/src/web3_subscriptions.ts]: Your changes indicate that `err` is/can be the expected return data. Does anyone @web3/web3-js know why `err` is the first argument for `messageListener`?

Comment (Spacesai1or) [reply packages/web3-core/src/web3_subscriptions.ts]: From the [Examples section](https://eips.ethereum.org/EIPS/eip-1193#appendix-ii-examples) of EIP-1193, it would appear the a failure to subscribe would reject the promise, not that an error would be sent as a `message`

```typescript
// Example 4: Log new blocks
ethereum
  .request({
    method: 'eth_subscribe',
    params: ['newHeads'],
  })
  .then((subscriptionId) => {
    ethereum.on('message', (message) => {
      if (message.type === 'eth_subscription') {
        const { data } = message;
        if (data.subscription === subscriptionId) {
          if ('result' in data && typeof data.result === 'object') {
            const block = data.result;
            console.log(`New block ${block.number}:`, block);
          } else {
            console.error(`Something went wrong: ${data.result}`);
          }
        }
      }
    });
  })
  .catch((error) => {
    console.error(
      `Error making newHeads subscription: ${error.message}.
       Code: ${error.code}. Data: ${error.data}`
    );
  });
```

This would mean `messageListener` is never called with an `err`?

File: packages/web3-core/src/web3_subscriptions.ts [hunk 2]
```diff
@@ -71,14 +72,24 @@ export abstract class Web3Subscription<
...
-			if (err) {
-				this._processSubscriptionError(err);
+
+			if (
+				data &&
+				jsonRpc.isResponseWithNotification(
+					data as unknown as JsonRpcSubscriptionResult | JsonRpcNotification<Log>,
+				)
+			) {
+				this._processSubscriptionResult(data?.params.result);
```
Comment (Spacesai1or) [inline packages/web3-core/src/web3_subscriptions.ts:93]: Judging from [this 1.x code](https://github.com/web3/web3.js/blob/13a2edc852aa2ae35cf827f8b08958c26356db4c/packages/web3-core-requestmanager/src/index.js#L109-L118), it seems like this code is to support legacy providers while `data.data.result` (what you have marked as `// for old providers`) is to support EIP-1193

However, to handle the legacy provider, it would appear that we're missing an event listener for `data` event, as `messageListener` is only triggered for `message` events

Comment (avkos) [reply packages/web3-core/src/web3_subscriptions.ts:93]: thanks. I've added support for old providers and change comment

File: packages/web3-core/src/web3_subscriptions.ts [hunk 3]
```diff
@@ -71,18 +72,33 @@ export abstract class Web3Subscription<
...
 			}
 		};
 
-		(this._requestManager.provider as Web3BaseProvider).on<Log>('message', messageListener);
+		// @ts-expect-error subscribe using old providers
+		if ((typeof this._requestManager.provider as Web3BaseProvider).request === 'function') {
+			(this._requestManager.provider as Web3BaseProvider).on<Log>('data', messageListener);
+		} else {
+			(this._requestManager.provider as Web3BaseProvider).on<Log>('message', messageListener);
+		}
```
Comment (spacesailor24) [inline packages/web3-core/src/web3_subscriptions.ts:101]: This is backwards, [it should be](https://github.com/web3/web3.js/blob/13a2edc852aa2ae35cf827f8b08958c26356db4c/packages/web3-core-requestmanager/src/index.js#L100-L101)

```typescript
if ((typeof this._requestManager.provider as Web3BaseProvider).request === 'function') {
			(this._requestManager.provider as Web3BaseProvider).on<Log>('message', messageListener);
		} else {
			(this._requestManager.provider as Web3BaseProvider).on<Log>('data', messageListener);
		}
```

Comment (Spacesai1or) [inline packages/web3-core/src/web3_subscriptions.ts]: This is backwards, [it should be](https://github.com/web3/web3.js/blob/13a2edc852aa2ae35cf827f8b08958c26356db4c/packages/web3-core-requestmanager/src/index.js#L100-L101)

```suggestion
		if ((typeof this._requestManager.provider as Web3BaseProvider).request === 'function') {
			(this._requestManager.provider as Web3BaseProvider).on<Log>('message', messageListener);
		} else {
			(this._requestManager.provider as Web3BaseProvider).on<Log>('data', messageListener);
		}
```

**Review by Spacesai1or — APPROVED** [review]
Otherwise looks good, thank you

**Review by jdevcs — APPROVED** [review]
@avkos update change log before merging

File: packages/web3-core/src/web3_subscriptions.ts (hunk 3 above)
Comment (avkos) [reply packages/web3-core/src/web3_subscriptions.ts]: omg! yes. thank you @spacesailor24 !
