### PR TITLE
[Quorum] Fix #2766, timestamp is not present on a Quorum node

### LINKED ISSUE #2766: getBlock by number or hash does not work on Quorum
### Description 
The getBlock method with a hash or a number as parameter does not work with a quorum permisionless blockchain

#### Expected behavior

    Calling `await web3.eth.getBlock(1)` or `await web3.eth.getBlock('0x000...')` should return an object.

#### Actual behavior

    Calling `await web3.eth.getBlock(1)` or `await web3.eth.getBlock('0x000...')` is throwing an error `Number can only safely store up to 53 bits` from bn.js.

#### Steps to reproduce the behavior

Install a quorum chain, connect to it and then 
```js
const web3 = new Web3('http://localhost:20200');
const block = await web3.eth.getBlock(1);
//const block = await web3.eth.getBlock('0x000...');

console.log(block);

// Throw 'Number can only safely store up to 53 bits'
```

#### Error Logs 

'Number can only safely store up to 53 bits'

### Versions 
* web3.js: 1.0.0-beta.53
* nodejs: v11.14.0
* ethereum node: N/A
* Quorum node: 2.2.0

### PR DESCRIPTION
**Pull request by oktapodia**
## Description

This PR fix the #2766 issue on quorum node 

I made the `timestamp` field from the `getBlock` response as optional + added the according test.

## Type of change

- [X] Bug fix 
- [ ] New feature 
- [ ] Breaking change
- [ ] Enhancement

## Checklist:

- [X] I have selected the correct base branch.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no warnings.
- [ ] I have updated or added types for all modules I've changed
- [ ] Any dependent changes have been merged and published in downstream modules.
- [X] I ran ```npm run test``` in the root folder with success and extended the tests if necessary.
- [X] I ran ```npm run build``` in the root folder and tested it in the browser and with node.
- [X] I ran ```npm run dtslint``` in the root folder and tested that all my types are correct
- [X] I have tested my code on an ethereum test network.
- [X] I have tested my code on a quorum test network.

### CODE REVIEW

**Review by nivida — APPROVED** [review]

File: packages/web3-core-helpers/src/Formatters.js [hunk 1]
```diff
@@ -300,7 +300,11 @@ export const outputBlockFormatter = (block) => {
     block.gasLimit = Utils.hexToNumber(block.gasLimit);
     block.gasUsed = Utils.hexToNumber(block.gasUsed);
     block.size = Utils.hexToNumber(block.size);
-    block.timestamp = Utils.hexToNumber(block.timestamp);
+
+    // Support Quorum 2.2.0 - timestamp is not present in the Quorum getBlock response
+    if (block.timestamp !== null) {
+        block.timestamp = Utils.hexToNumber(block.timestamp);
```
Comment (jimmy-dg) [inline packages/web3-core-helpers/src/Formatters.js:306]: @nivida I'm using Quorum 2.2.1 and I'm getting this timestamp value `0x159c6ca1c661d27c`, which causes an error.
